<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LopHocPhanTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('lop_hoc_phan')->delete();
        
        \DB::table('lop_hoc_phan')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ma_lop_hoc_phan' => 'LHP01001',
                'ten_lop' => 'Quản trị mạng Windows Server - Nhóm 1',
                'mon_hoc_id' => 16,
                'giang_vien_id' => 12,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2023-09-09 07:14:00',
                'ngay_cap_nhat' => '2023-09-09 07:14:00',
            ),
            1 => 
            array (
                'id' => 2,
                'ma_lop_hoc_phan' => 'LHP01002',
                'ten_lop' => 'Lập trình Web với PHP - Nhóm 2',
                'mon_hoc_id' => 5,
                'giang_vien_id' => 7,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-20 22:41:00',
                'ngay_cap_nhat' => '2025-08-20 22:41:00',
            ),
            2 => 
            array (
                'id' => 3,
                'ma_lop_hoc_phan' => 'LHP01003',
                'ten_lop' => 'Cấu trúc dữ liệu và giải thuật - Nhóm 3',
                'mon_hoc_id' => 2,
                'giang_vien_id' => 13,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-03-09 20:53:00',
                'ngay_cap_nhat' => '2024-03-09 20:53:00',
            ),
            3 => 
            array (
                'id' => 4,
                'ma_lop_hoc_phan' => 'LHP01004',
                'ten_lop' => 'Lập trình căn bản C - Nhóm 1',
                'mon_hoc_id' => 1,
                'giang_vien_id' => 2,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-09-17 03:35:00',
                'ngay_cap_nhat' => '2025-09-17 03:35:00',
            ),
            4 => 
            array (
                'id' => 5,
                'ma_lop_hoc_phan' => 'LHP01005',
                'ten_lop' => 'An toàn thông tin - Nhóm 2',
                'mon_hoc_id' => 9,
                'giang_vien_id' => 16,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-04-08 13:42:00',
                'ngay_cap_nhat' => '2025-04-08 13:42:00',
            ),
            5 => 
            array (
                'id' => 6,
                'ma_lop_hoc_phan' => 'LHP01006',
                'ten_lop' => 'Cơ sở dữ liệu - Nhóm 3',
                'mon_hoc_id' => 4,
                'giang_vien_id' => 17,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-03-02 16:46:00',
                'ngay_cap_nhat' => '2024-03-02 16:46:00',
            ),
            6 => 
            array (
                'id' => 7,
                'ma_lop_hoc_phan' => 'LHP01007',
                'ten_lop' => 'Đồ án chuyên ngành CNTT - Nhóm 1',
                'mon_hoc_id' => 20,
                'giang_vien_id' => 4,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-05-16 06:38:00',
                'ngay_cap_nhat' => '2026-05-16 06:38:00',
            ),
            7 => 
            array (
                'id' => 8,
                'ma_lop_hoc_phan' => 'LHP01008',
                'ten_lop' => 'Phát triển ứng dụng di động Android - Nhóm 2',
                'mon_hoc_id' => 7,
                'giang_vien_id' => 9,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2025-11-17 09:10:00',
                'ngay_cap_nhat' => '2025-11-17 09:10:00',
            ),
            8 => 
            array (
                'id' => 9,
                'ma_lop_hoc_phan' => 'LHP01009',
                'ten_lop' => 'Cấu trúc dữ liệu và giải thuật - Nhóm 3',
                'mon_hoc_id' => 2,
                'giang_vien_id' => 18,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-06-08 07:00:00',
                'ngay_cap_nhat' => '2025-06-08 07:00:00',
            ),
            9 => 
            array (
                'id' => 10,
                'ma_lop_hoc_phan' => 'LHP01010',
                'ten_lop' => 'Lập trình căn bản C - Nhóm 1',
                'mon_hoc_id' => 1,
                'giang_vien_id' => 3,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-02-01 16:04:00',
                'ngay_cap_nhat' => '2024-02-01 16:04:00',
            ),
            10 => 
            array (
                'id' => 11,
                'ma_lop_hoc_phan' => 'LHP02001',
                'ten_lop' => 'Kỹ thuật hàn - Nhóm 1',
                'mon_hoc_id' => 32,
                'giang_vien_id' => 20,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-03-29 08:29:00',
                'ngay_cap_nhat' => '2025-03-29 08:29:00',
            ),
            11 => 
            array (
                'id' => 12,
                'ma_lop_hoc_phan' => 'LHP02002',
                'ten_lop' => 'Vẽ kỹ thuật cơ khí - Nhóm 2',
                'mon_hoc_id' => 21,
                'giang_vien_id' => 20,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2025-08-07 21:20:00',
                'ngay_cap_nhat' => '2025-08-07 21:20:00',
            ),
            12 => 
            array (
                'id' => 13,
                'ma_lop_hoc_phan' => 'LHP02003',
                'ten_lop' => 'Vật liệu học - Nhóm 3',
                'mon_hoc_id' => 27,
                'giang_vien_id' => 20,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-05-10 21:41:00',
                'ngay_cap_nhat' => '2024-05-10 21:41:00',
            ),
            13 => 
            array (
                'id' => 14,
                'ma_lop_hoc_phan' => 'LHP02004',
                'ten_lop' => 'Nguyên lý máy - Nhóm 1',
                'mon_hoc_id' => 23,
                'giang_vien_id' => 24,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-02-07 11:52:00',
                'ngay_cap_nhat' => '2024-02-07 11:52:00',
            ),
            14 => 
            array (
                'id' => 15,
                'ma_lop_hoc_phan' => 'LHP02005',
                'ten_lop' => 'Gia công CNC - Nhóm 2',
                'mon_hoc_id' => 26,
                'giang_vien_id' => 21,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-02-20 08:53:00',
                'ngay_cap_nhat' => '2026-02-20 08:53:00',
            ),
            15 => 
            array (
                'id' => 16,
                'ma_lop_hoc_phan' => 'LHP02006',
                'ten_lop' => 'Vật liệu học - Nhóm 3',
                'mon_hoc_id' => 27,
                'giang_vien_id' => 26,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-04-28 22:46:00',
                'ngay_cap_nhat' => '2024-04-28 22:46:00',
            ),
            16 => 
            array (
                'id' => 17,
                'ma_lop_hoc_phan' => 'LHP02007',
                'ten_lop' => 'Vẽ kỹ thuật cơ khí - Nhóm 1',
                'mon_hoc_id' => 21,
                'giang_vien_id' => 21,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-01-14 05:39:00',
                'ngay_cap_nhat' => '2026-01-14 05:39:00',
            ),
            17 => 
            array (
                'id' => 18,
                'ma_lop_hoc_phan' => 'LHP02008',
                'ten_lop' => 'Vật liệu học - Nhóm 2',
                'mon_hoc_id' => 27,
                'giang_vien_id' => 24,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-04-16 15:07:00',
                'ngay_cap_nhat' => '2026-04-16 15:07:00',
            ),
            18 => 
            array (
                'id' => 19,
                'ma_lop_hoc_phan' => 'LHP02009',
                'ten_lop' => 'Thiết kế khuôn mẫu - Nhóm 3',
                'mon_hoc_id' => 35,
                'giang_vien_id' => 25,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-17 20:20:00',
                'ngay_cap_nhat' => '2025-01-17 20:20:00',
            ),
            19 => 
            array (
                'id' => 20,
                'ma_lop_hoc_phan' => 'LHP02010',
                'ten_lop' => 'Vẽ kỹ thuật cơ khí - Nhóm 1',
                'mon_hoc_id' => 21,
                'giang_vien_id' => 27,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-02-12 13:42:00',
                'ngay_cap_nhat' => '2024-02-12 13:42:00',
            ),
            20 => 
            array (
                'id' => 21,
                'ma_lop_hoc_phan' => 'LHP03001',
                'ten_lop' => 'Mạng viễn thông - Nhóm 1',
                'mon_hoc_id' => 47,
                'giang_vien_id' => 31,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-05-31 17:57:00',
                'ngay_cap_nhat' => '2024-05-31 17:57:00',
            ),
            21 => 
            array (
                'id' => 22,
                'ma_lop_hoc_phan' => 'LHP03002',
                'ten_lop' => 'Kỹ thuật số - Nhóm 2',
                'mon_hoc_id' => 45,
                'giang_vien_id' => 28,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-05-12 05:04:00',
                'ngay_cap_nhat' => '2026-05-12 05:04:00',
            ),
            22 => 
            array (
                'id' => 23,
                'ma_lop_hoc_phan' => 'LHP03003',
                'ten_lop' => 'Thiết kế mạch điện tử - Nhóm 3',
                'mon_hoc_id' => 48,
                'giang_vien_id' => 35,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2025-02-20 01:32:00',
                'ngay_cap_nhat' => '2025-02-20 01:32:00',
            ),
            23 => 
            array (
                'id' => 24,
                'ma_lop_hoc_phan' => 'LHP03004',
                'ten_lop' => 'Truyền động điện - Nhóm 1',
                'mon_hoc_id' => 39,
                'giang_vien_id' => 36,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-01-09 14:28:00',
                'ngay_cap_nhat' => '2024-01-09 14:28:00',
            ),
            24 => 
            array (
                'id' => 25,
                'ma_lop_hoc_phan' => 'LHP03005',
                'ten_lop' => 'Thiết kế mạch điện tử - Nhóm 2',
                'mon_hoc_id' => 48,
                'giang_vien_id' => 37,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-02-01 10:07:00',
                'ngay_cap_nhat' => '2026-02-01 10:07:00',
            ),
            25 => 
            array (
                'id' => 26,
                'ma_lop_hoc_phan' => 'LHP03006',
                'ten_lop' => 'Hệ thống cung cấp điện - Nhóm 3',
                'mon_hoc_id' => 43,
                'giang_vien_id' => 39,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-11-22 01:35:00',
                'ngay_cap_nhat' => '2025-11-22 01:35:00',
            ),
            26 => 
            array (
                'id' => 27,
                'ma_lop_hoc_phan' => 'LHP03007',
                'ten_lop' => 'Điện tử công suất - Nhóm 1',
                'mon_hoc_id' => 44,
                'giang_vien_id' => 28,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-02-20 10:23:00',
                'ngay_cap_nhat' => '2026-02-20 10:23:00',
            ),
            27 => 
            array (
                'id' => 28,
                'ma_lop_hoc_phan' => 'LHP03008',
                'ten_lop' => 'Đồ án điện tử viễn thông - Nhóm 2',
                'mon_hoc_id' => 49,
                'giang_vien_id' => 28,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2026-03-26 22:42:00',
                'ngay_cap_nhat' => '2026-03-26 22:42:00',
            ),
            28 => 
            array (
                'id' => 29,
                'ma_lop_hoc_phan' => 'LHP03009',
                'ten_lop' => 'PLC cơ bản - Nhóm 3',
                'mon_hoc_id' => 41,
                'giang_vien_id' => 39,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-28 00:21:00',
                'ngay_cap_nhat' => '2024-10-28 00:21:00',
            ),
            29 => 
            array (
                'id' => 30,
                'ma_lop_hoc_phan' => 'LHP03010',
                'ten_lop' => 'PLC cơ bản - Nhóm 1',
                'mon_hoc_id' => 41,
                'giang_vien_id' => 38,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2023-11-02 05:31:00',
                'ngay_cap_nhat' => '2023-11-02 05:31:00',
            ),
            30 => 
            array (
                'id' => 31,
                'ma_lop_hoc_phan' => 'LHP04001',
                'ten_lop' => 'Khung gầm ô tô - Nhóm 1',
                'mon_hoc_id' => 52,
                'giang_vien_id' => 47,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-09-05 06:07:00',
                'ngay_cap_nhat' => '2024-09-05 06:07:00',
            ),
            31 => 
            array (
                'id' => 32,
                'ma_lop_hoc_phan' => 'LHP04002',
                'ten_lop' => 'Hệ thống truyền lực ô tô - Nhóm 2',
                'mon_hoc_id' => 56,
                'giang_vien_id' => 42,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-03-08 13:02:00',
                'ngay_cap_nhat' => '2024-03-08 13:02:00',
            ),
            32 => 
            array (
                'id' => 33,
                'ma_lop_hoc_phan' => 'LHP04003',
                'ten_lop' => 'Thực hành động cơ diesel - Nhóm 3',
                'mon_hoc_id' => 59,
                'giang_vien_id' => 41,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-05-18 00:33:00',
                'ngay_cap_nhat' => '2026-05-18 00:33:00',
            ),
            33 => 
            array (
                'id' => 34,
                'ma_lop_hoc_phan' => 'LHP04004',
                'ten_lop' => 'Động cơ đốt trong - Nhóm 1',
                'mon_hoc_id' => 50,
                'giang_vien_id' => 45,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-21 23:52:00',
                'ngay_cap_nhat' => '2024-07-21 23:52:00',
            ),
            34 => 
            array (
                'id' => 35,
                'ma_lop_hoc_phan' => 'LHP04005',
                'ten_lop' => 'Khung gầm ô tô - Nhóm 2',
                'mon_hoc_id' => 52,
                'giang_vien_id' => 41,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-12-05 19:58:00',
                'ngay_cap_nhat' => '2025-12-05 19:58:00',
            ),
            35 => 
            array (
                'id' => 36,
                'ma_lop_hoc_phan' => 'LHP04006',
                'ten_lop' => 'Kỹ thuật sửa chữa ô tô - Nhóm 3',
                'mon_hoc_id' => 53,
                'giang_vien_id' => 43,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2026-02-13 04:08:00',
                'ngay_cap_nhat' => '2026-02-13 04:08:00',
            ),
            36 => 
            array (
                'id' => 37,
                'ma_lop_hoc_phan' => 'LHP04007',
                'ten_lop' => 'Hệ thống truyền lực ô tô - Nhóm 1',
                'mon_hoc_id' => 56,
                'giang_vien_id' => 45,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-10-19 06:13:00',
                'ngay_cap_nhat' => '2024-10-19 06:13:00',
            ),
            37 => 
            array (
                'id' => 38,
                'ma_lop_hoc_phan' => 'LHP04008',
                'ten_lop' => 'Thực hành động cơ diesel - Nhóm 2',
                'mon_hoc_id' => 59,
                'giang_vien_id' => 46,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-30 16:34:00',
                'ngay_cap_nhat' => '2024-07-30 16:34:00',
            ),
            38 => 
            array (
                'id' => 39,
                'ma_lop_hoc_phan' => 'LHP04009',
                'ten_lop' => 'Cơ điện tử ô tô - Nhóm 3',
                'mon_hoc_id' => 55,
                'giang_vien_id' => 46,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-12-02 21:47:00',
                'ngay_cap_nhat' => '2025-12-02 21:47:00',
            ),
            39 => 
            array (
                'id' => 40,
                'ma_lop_hoc_phan' => 'LHP04010',
                'ten_lop' => 'Thực hành động cơ xăng - Nhóm 1',
                'mon_hoc_id' => 58,
                'giang_vien_id' => 43,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2023-09-21 12:09:00',
                'ngay_cap_nhat' => '2023-09-21 12:09:00',
            ),
            40 => 
            array (
                'id' => 41,
                'ma_lop_hoc_phan' => 'LHP05001',
                'ten_lop' => 'Nguyên lý kế toán - Nhóm 1',
                'mon_hoc_id' => 60,
                'giang_vien_id' => 58,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-06-25 09:43:00',
                'ngay_cap_nhat' => '2024-06-25 09:43:00',
            ),
            41 => 
            array (
                'id' => 42,
                'ma_lop_hoc_phan' => 'LHP05002',
                'ten_lop' => 'Quản trị học - Nhóm 2',
                'mon_hoc_id' => 64,
                'giang_vien_id' => 50,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2023-10-06 11:52:00',
                'ngay_cap_nhat' => '2023-10-06 11:52:00',
            ),
            42 => 
            array (
                'id' => 43,
                'ma_lop_hoc_phan' => 'LHP05003',
                'ten_lop' => 'Kiểm toán căn bản - Nhóm 3',
                'mon_hoc_id' => 67,
                'giang_vien_id' => 49,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-11-29 16:50:00',
                'ngay_cap_nhat' => '2024-11-29 16:50:00',
            ),
            43 => 
            array (
                'id' => 44,
                'ma_lop_hoc_phan' => 'LHP05004',
                'ten_lop' => 'Khởi nghiệp kinh doanh - Nhóm 1',
                'mon_hoc_id' => 71,
                'giang_vien_id' => 52,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-12-01 21:20:00',
                'ngay_cap_nhat' => '2025-12-01 21:20:00',
            ),
            44 => 
            array (
                'id' => 45,
                'ma_lop_hoc_phan' => 'LHP05005',
                'ten_lop' => 'Quản trị nhân sự - Nhóm 2',
                'mon_hoc_id' => 68,
                'giang_vien_id' => 48,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-01-24 07:58:00',
                'ngay_cap_nhat' => '2026-01-24 07:58:00',
            ),
            45 => 
            array (
                'id' => 46,
                'ma_lop_hoc_phan' => 'LHP05006',
                'ten_lop' => 'Phân tích báo cáo tài chính - Nhóm 3',
                'mon_hoc_id' => 70,
                'giang_vien_id' => 59,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-25 14:11:00',
                'ngay_cap_nhat' => '2025-03-25 14:11:00',
            ),
            46 => 
            array (
                'id' => 47,
                'ma_lop_hoc_phan' => 'LHP05007',
                'ten_lop' => 'Phân tích báo cáo tài chính - Nhóm 1',
                'mon_hoc_id' => 70,
                'giang_vien_id' => 49,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-11 01:27:00',
                'ngay_cap_nhat' => '2025-09-11 01:27:00',
            ),
            47 => 
            array (
                'id' => 48,
                'ma_lop_hoc_phan' => 'LHP05008',
                'ten_lop' => 'Quản trị học - Nhóm 2',
                'mon_hoc_id' => 64,
                'giang_vien_id' => 56,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-04 00:21:00',
                'ngay_cap_nhat' => '2025-01-04 00:21:00',
            ),
            48 => 
            array (
                'id' => 49,
                'ma_lop_hoc_phan' => 'LHP05009',
                'ten_lop' => 'Kiểm toán căn bản - Nhóm 3',
                'mon_hoc_id' => 67,
                'giang_vien_id' => 59,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-22 19:03:00',
                'ngay_cap_nhat' => '2025-05-22 19:03:00',
            ),
            49 => 
            array (
                'id' => 50,
                'ma_lop_hoc_phan' => 'LHP05010',
                'ten_lop' => 'Phân tích báo cáo tài chính - Nhóm 1',
                'mon_hoc_id' => 70,
                'giang_vien_id' => 57,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2023-12-28 22:20:00',
                'ngay_cap_nhat' => '2023-12-28 22:20:00',
            ),
            50 => 
            array (
                'id' => 51,
                'ma_lop_hoc_phan' => 'LHP06001',
                'ten_lop' => 'Đồ án kết cấu bê tông - Nhóm 1',
                'mon_hoc_id' => 80,
                'giang_vien_id' => 63,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-11-29 17:34:00',
                'ngay_cap_nhat' => '2025-11-29 17:34:00',
            ),
            51 => 
            array (
                'id' => 52,
                'ma_lop_hoc_phan' => 'LHP06002',
                'ten_lop' => 'Nền và móng - Nhóm 2',
                'mon_hoc_id' => 78,
                'giang_vien_id' => 61,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-06-10 10:23:00',
                'ngay_cap_nhat' => '2025-06-10 10:23:00',
            ),
            52 => 
            array (
                'id' => 53,
                'ma_lop_hoc_phan' => 'LHP06003',
                'ten_lop' => 'Kỹ thuật thi công - Nhóm 3',
                'mon_hoc_id' => 76,
                'giang_vien_id' => 63,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-03-22 21:22:00',
                'ngay_cap_nhat' => '2024-03-22 21:22:00',
            ),
            53 => 
            array (
                'id' => 54,
                'ma_lop_hoc_phan' => 'LHP06004',
                'ten_lop' => 'Autocad xây dựng - Nhóm 1',
                'mon_hoc_id' => 79,
                'giang_vien_id' => 63,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-19 12:58:00',
                'ngay_cap_nhat' => '2025-05-19 12:58:00',
            ),
            54 => 
            array (
                'id' => 55,
                'ma_lop_hoc_phan' => 'LHP06005',
                'ten_lop' => 'Cơ học đất - Nhóm 2',
                'mon_hoc_id' => 73,
                'giang_vien_id' => 66,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-06-24 11:32:00',
                'ngay_cap_nhat' => '2026-06-24 11:32:00',
            ),
            55 => 
            array (
                'id' => 56,
                'ma_lop_hoc_phan' => 'LHP06006',
                'ten_lop' => 'Đồ án kết cấu bê tông - Nhóm 3',
                'mon_hoc_id' => 80,
                'giang_vien_id' => 67,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-08-29 10:32:00',
                'ngay_cap_nhat' => '2024-08-29 10:32:00',
            ),
            56 => 
            array (
                'id' => 57,
                'ma_lop_hoc_phan' => 'LHP06007',
                'ten_lop' => 'Cơ học đất - Nhóm 1',
                'mon_hoc_id' => 73,
                'giang_vien_id' => 61,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-05 21:40:00',
                'ngay_cap_nhat' => '2024-10-05 21:40:00',
            ),
            57 => 
            array (
                'id' => 58,
                'ma_lop_hoc_phan' => 'LHP06008',
                'ten_lop' => 'Vật liệu xây dựng - Nhóm 2',
                'mon_hoc_id' => 75,
                'giang_vien_id' => 66,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2023-12-26 23:43:00',
                'ngay_cap_nhat' => '2023-12-26 23:43:00',
            ),
            58 => 
            array (
                'id' => 59,
                'ma_lop_hoc_phan' => 'LHP06009',
                'ten_lop' => 'Kết cấu công trình - Nhóm 3',
                'mon_hoc_id' => 74,
                'giang_vien_id' => 60,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-01-27 02:03:00',
                'ngay_cap_nhat' => '2024-01-27 02:03:00',
            ),
            59 => 
            array (
                'id' => 60,
                'ma_lop_hoc_phan' => 'LHP06010',
                'ten_lop' => 'Kết cấu công trình - Nhóm 1',
                'mon_hoc_id' => 74,
                'giang_vien_id' => 64,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-11 13:24:00',
                'ngay_cap_nhat' => '2025-01-11 13:24:00',
            ),
            60 => 
            array (
                'id' => 61,
                'ma_lop_hoc_phan' => 'LHP07001',
                'ten_lop' => 'Biên dịch Anh - Việt - Nhóm 1',
                'mon_hoc_id' => 88,
                'giang_vien_id' => 74,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-06 21:07:00',
                'ngay_cap_nhat' => '2025-10-06 21:07:00',
            ),
            61 => 
            array (
                'id' => 62,
                'ma_lop_hoc_phan' => 'LHP07002',
                'ten_lop' => 'Anh văn căn bản 1 - Nhóm 2',
                'mon_hoc_id' => 81,
                'giang_vien_id' => 77,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-02 16:06:00',
                'ngay_cap_nhat' => '2025-08-02 16:06:00',
            ),
            62 => 
            array (
                'id' => 63,
                'ma_lop_hoc_phan' => 'LHP07003',
                'ten_lop' => 'Nhật văn cơ sở 1 - Nhóm 3',
                'mon_hoc_id' => 85,
                'giang_vien_id' => 72,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2026-01-13 12:25:00',
                'ngay_cap_nhat' => '2026-01-13 12:25:00',
            ),
            63 => 
            array (
                'id' => 64,
                'ma_lop_hoc_phan' => 'LHP07004',
                'ten_lop' => 'Anh văn căn bản 1 - Nhóm 1',
                'mon_hoc_id' => 81,
                'giang_vien_id' => 75,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-09 17:18:00',
                'ngay_cap_nhat' => '2025-10-09 17:18:00',
            ),
            64 => 
            array (
                'id' => 65,
                'ma_lop_hoc_phan' => 'LHP07005',
                'ten_lop' => 'Anh văn giao tiếp - Nhóm 2',
                'mon_hoc_id' => 83,
                'giang_vien_id' => 72,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-04-09 01:00:00',
                'ngay_cap_nhat' => '2024-04-09 01:00:00',
            ),
            65 => 
            array (
                'id' => 66,
                'ma_lop_hoc_phan' => 'LHP07006',
                'ten_lop' => 'Kỹ năng nghe nói tiếng Anh - Nhóm 3',
                'mon_hoc_id' => 87,
                'giang_vien_id' => 76,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-10-04 23:47:00',
                'ngay_cap_nhat' => '2024-10-04 23:47:00',
            ),
            66 => 
            array (
                'id' => 67,
                'ma_lop_hoc_phan' => 'LHP07007',
                'ten_lop' => 'Nhật văn cơ sở 2 - Nhóm 1',
                'mon_hoc_id' => 86,
                'giang_vien_id' => 71,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-08-11 07:39:00',
                'ngay_cap_nhat' => '2024-08-11 07:39:00',
            ),
            67 => 
            array (
                'id' => 68,
                'ma_lop_hoc_phan' => 'LHP07008',
                'ten_lop' => 'Nhật văn cơ sở 1 - Nhóm 2',
                'mon_hoc_id' => 85,
                'giang_vien_id' => 71,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-03-02 20:35:00',
                'ngay_cap_nhat' => '2026-03-02 20:35:00',
            ),
            68 => 
            array (
                'id' => 69,
                'ma_lop_hoc_phan' => 'LHP07009',
                'ten_lop' => 'Anh văn căn bản 2 - Nhóm 3',
                'mon_hoc_id' => 82,
                'giang_vien_id' => 72,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-08 23:37:00',
                'ngay_cap_nhat' => '2024-09-08 23:37:00',
            ),
            69 => 
            array (
                'id' => 70,
                'ma_lop_hoc_phan' => 'LHP07010',
                'ten_lop' => 'Biên dịch Anh - Việt - Nhóm 1',
                'mon_hoc_id' => 88,
                'giang_vien_id' => 73,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-02-21 09:39:00',
                'ngay_cap_nhat' => '2024-02-21 09:39:00',
            ),
            70 => 
            array (
                'id' => 71,
                'ma_lop_hoc_phan' => 'LHP08001',
                'ten_lop' => 'Hóa phân tích đại cương - Nhóm 1',
                'mon_hoc_id' => 89,
                'giang_vien_id' => 79,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-06-03 19:42:00',
                'ngay_cap_nhat' => '2025-06-03 19:42:00',
            ),
            71 => 
            array (
                'id' => 72,
                'ma_lop_hoc_phan' => 'LHP08002',
                'ten_lop' => 'Hóa vô cơ - Nhóm 2',
                'mon_hoc_id' => 91,
                'giang_vien_id' => 83,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2025-05-09 13:10:00',
                'ngay_cap_nhat' => '2025-05-09 13:10:00',
            ),
            72 => 
            array (
                'id' => 73,
                'ma_lop_hoc_phan' => 'LHP08003',
                'ten_lop' => 'Hóa phân tích đại cương - Nhóm 3',
                'mon_hoc_id' => 89,
                'giang_vien_id' => 80,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-02-17 11:08:00',
                'ngay_cap_nhat' => '2025-02-17 11:08:00',
            ),
            73 => 
            array (
                'id' => 74,
                'ma_lop_hoc_phan' => 'LHP08004',
                'ten_lop' => 'Hóa lý - Nhóm 1',
                'mon_hoc_id' => 94,
                'giang_vien_id' => 83,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-01-29 11:49:00',
                'ngay_cap_nhat' => '2026-01-29 11:49:00',
            ),
            74 => 
            array (
                'id' => 75,
                'ma_lop_hoc_phan' => 'LHP08005',
                'ten_lop' => 'Hóa vô cơ - Nhóm 2',
                'mon_hoc_id' => 91,
                'giang_vien_id' => 81,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-01-15 08:54:00',
                'ngay_cap_nhat' => '2024-01-15 08:54:00',
            ),
            75 => 
            array (
                'id' => 76,
                'ma_lop_hoc_phan' => 'LHP08006',
                'ten_lop' => 'Công nghệ vật liệu polymer - Nhóm 3',
                'mon_hoc_id' => 95,
                'giang_vien_id' => 79,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-01-04 23:04:00',
                'ngay_cap_nhat' => '2024-01-04 23:04:00',
            ),
            76 => 
            array (
                'id' => 77,
                'ma_lop_hoc_phan' => 'LHP08007',
                'ten_lop' => 'Hóa phân tích đại cương - Nhóm 1',
                'mon_hoc_id' => 89,
                'giang_vien_id' => 84,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-10-09 01:35:00',
                'ngay_cap_nhat' => '2024-10-09 01:35:00',
            ),
            77 => 
            array (
                'id' => 78,
                'ma_lop_hoc_phan' => 'LHP08008',
                'ten_lop' => 'Hóa vô cơ - Nhóm 2',
                'mon_hoc_id' => 91,
                'giang_vien_id' => 82,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-19 12:14:00',
                'ngay_cap_nhat' => '2025-08-19 12:14:00',
            ),
            78 => 
            array (
                'id' => 79,
                'ma_lop_hoc_phan' => 'LHP08009',
                'ten_lop' => 'Công nghệ vật liệu polymer - Nhóm 3',
                'mon_hoc_id' => 95,
                'giang_vien_id' => 82,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-05-23 16:05:00',
                'ngay_cap_nhat' => '2026-05-23 16:05:00',
            ),
            79 => 
            array (
                'id' => 80,
                'ma_lop_hoc_phan' => 'LHP08010',
                'ten_lop' => 'Công nghệ xử lý nước thải - Nhóm 1',
                'mon_hoc_id' => 92,
                'giang_vien_id' => 80,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-05 16:08:00',
                'ngay_cap_nhat' => '2024-07-05 16:08:00',
            ),
            80 => 
            array (
                'id' => 81,
                'ma_lop_hoc_phan' => 'LHP09001',
                'ten_lop' => 'Tâm lý khách du lịch - Nhóm 1',
                'mon_hoc_id' => 103,
                'giang_vien_id' => 87,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-08-04 01:14:00',
                'ngay_cap_nhat' => '2025-08-04 01:14:00',
            ),
            81 => 
            array (
                'id' => 82,
                'ma_lop_hoc_phan' => 'LHP09002',
                'ten_lop' => 'Tâm lý khách du lịch - Nhóm 2',
                'mon_hoc_id' => 103,
                'giang_vien_id' => 88,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-11-22 01:42:00',
                'ngay_cap_nhat' => '2024-11-22 01:42:00',
            ),
            82 => 
            array (
                'id' => 83,
                'ma_lop_hoc_phan' => 'LHP09003',
                'ten_lop' => 'Quản trị khách sạn - Nhóm 3',
                'mon_hoc_id' => 99,
                'giang_vien_id' => 90,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2023-11-04 01:41:00',
                'ngay_cap_nhat' => '2023-11-04 01:41:00',
            ),
            83 => 
            array (
                'id' => 84,
                'ma_lop_hoc_phan' => 'LHP09004',
                'ten_lop' => 'Văn hóa du lịch - Nhóm 1',
                'mon_hoc_id' => 101,
                'giang_vien_id' => 86,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-07-22 12:41:00',
                'ngay_cap_nhat' => '2024-07-22 12:41:00',
            ),
            84 => 
            array (
                'id' => 85,
                'ma_lop_hoc_phan' => 'LHP09005',
                'ten_lop' => 'Tổ chức sự kiện - Nhóm 2',
                'mon_hoc_id' => 102,
                'giang_vien_id' => 90,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2025-09-09 07:33:00',
                'ngay_cap_nhat' => '2025-09-09 07:33:00',
            ),
            85 => 
            array (
                'id' => 86,
                'ma_lop_hoc_phan' => 'LHP09006',
                'ten_lop' => 'Tổ chức sự kiện - Nhóm 3',
                'mon_hoc_id' => 102,
                'giang_vien_id' => 90,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2023-08-14 16:56:00',
                'ngay_cap_nhat' => '2023-08-14 16:56:00',
            ),
            86 => 
            array (
                'id' => 87,
                'ma_lop_hoc_phan' => 'LHP09007',
                'ten_lop' => 'Nghiệp vụ buồng phòng - Nhóm 1',
                'mon_hoc_id' => 98,
                'giang_vien_id' => 92,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-06-19 20:17:00',
                'ngay_cap_nhat' => '2026-06-19 20:17:00',
            ),
            87 => 
            array (
                'id' => 88,
                'ma_lop_hoc_phan' => 'LHP09008',
                'ten_lop' => 'Quản trị khách sạn - Nhóm 2',
                'mon_hoc_id' => 99,
                'giang_vien_id' => 87,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-03-30 21:14:00',
                'ngay_cap_nhat' => '2024-03-30 21:14:00',
            ),
            88 => 
            array (
                'id' => 89,
                'ma_lop_hoc_phan' => 'LHP09009',
                'ten_lop' => 'Tổ chức sự kiện - Nhóm 3',
                'mon_hoc_id' => 102,
                'giang_vien_id' => 90,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2026-04-08 06:37:00',
                'ngay_cap_nhat' => '2026-04-08 06:37:00',
            ),
            89 => 
            array (
                'id' => 90,
                'ma_lop_hoc_phan' => 'LHP09010',
                'ten_lop' => 'Nghiệp vụ buồng phòng - Nhóm 1',
                'mon_hoc_id' => 98,
                'giang_vien_id' => 91,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-04-18 18:37:00',
                'ngay_cap_nhat' => '2024-04-18 18:37:00',
            ),
            90 => 
            array (
                'id' => 91,
                'ma_lop_hoc_phan' => 'LHP10001',
                'ten_lop' => 'Kinh tế chính trị Mác - Lênin - Nhóm 1',
                'mon_hoc_id' => 105,
                'giang_vien_id' => 95,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2023-11-23 05:16:00',
                'ngay_cap_nhat' => '2023-11-23 05:16:00',
            ),
            91 => 
            array (
                'id' => 92,
                'ma_lop_hoc_phan' => 'LHP10002',
                'ten_lop' => 'Kinh tế chính trị Mác - Lênin - Nhóm 2',
                'mon_hoc_id' => 105,
                'giang_vien_id' => 99,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_ket_thuc',
                'ngay_tao' => '2024-01-23 06:28:00',
                'ngay_cap_nhat' => '2024-01-23 06:28:00',
            ),
            92 => 
            array (
                'id' => 93,
                'ma_lop_hoc_phan' => 'LHP10003',
                'ten_lop' => 'Giáo dục thể chất 1 - Nhóm 3',
                'mon_hoc_id' => 108,
                'giang_vien_id' => 100,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-11-19 19:09:00',
                'ngay_cap_nhat' => '2025-11-19 19:09:00',
            ),
            93 => 
            array (
                'id' => 94,
                'ma_lop_hoc_phan' => 'LHP10004',
                'ten_lop' => 'Giáo dục quốc phòng - an ninh - Nhóm 1',
                'mon_hoc_id' => 110,
                'giang_vien_id' => 95,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 45,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-07-02 14:38:00',
                'ngay_cap_nhat' => '2025-07-02 14:38:00',
            ),
            94 => 
            array (
                'id' => 95,
                'ma_lop_hoc_phan' => 'LHP10005',
                'ten_lop' => 'Giáo dục thể chất 1 - Nhóm 2',
                'mon_hoc_id' => 108,
                'giang_vien_id' => 94,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-04-27 03:01:00',
                'ngay_cap_nhat' => '2024-04-27 03:01:00',
            ),
            95 => 
            array (
                'id' => 96,
                'ma_lop_hoc_phan' => 'LHP10006',
                'ten_lop' => 'Kinh tế chính trị Mác - Lênin - Nhóm 3',
                'mon_hoc_id' => 105,
                'giang_vien_id' => 99,
                'hoc_ky' => 'HK2',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 35,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-04-01 19:38:00',
                'ngay_cap_nhat' => '2026-04-01 19:38:00',
            ),
            96 => 
            array (
                'id' => 97,
                'ma_lop_hoc_phan' => 'LHP10007',
                'ten_lop' => 'Triết học Mác - Lênin - Nhóm 1',
                'mon_hoc_id' => 104,
                'giang_vien_id' => 94,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 50,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2023-08-03 21:41:00',
                'ngay_cap_nhat' => '2023-08-03 21:41:00',
            ),
            97 => 
            array (
                'id' => 98,
                'ma_lop_hoc_phan' => 'LHP10008',
                'ten_lop' => 'Pháp luật đại cương - Nhóm 2',
                'mon_hoc_id' => 107,
                'giang_vien_id' => 99,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-11-12 15:50:00',
                'ngay_cap_nhat' => '2024-11-12 15:50:00',
            ),
            98 => 
            array (
                'id' => 99,
                'ma_lop_hoc_phan' => 'LHP10009',
                'ten_lop' => 'Giáo dục quốc phòng - an ninh - Nhóm 3',
                'mon_hoc_id' => 110,
                'giang_vien_id' => 99,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2024-2025',
                'si_so_toi_da' => 35,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2024-05-01 08:30:00',
                'ngay_cap_nhat' => '2024-05-01 08:30:00',
            ),
            99 => 
            array (
                'id' => 100,
                'ma_lop_hoc_phan' => 'LHP10010',
                'ten_lop' => 'Giáo dục quốc phòng - an ninh - Nhóm 1',
                'mon_hoc_id' => 110,
                'giang_vien_id' => 96,
                'hoc_ky' => 'HK1',
                'nam_hoc' => '2023-2024',
                'si_so_toi_da' => 45,
                'trang_thai' => 'da_khoa',
                'ngay_tao' => '2025-01-09 06:00:00',
                'ngay_cap_nhat' => '2025-01-09 06:00:00',
            ),
            100 => 
            array (
                'id' => 101,
                'ma_lop_hoc_phan' => 'LHP_CXDK7',
                'ten_lop' => 'CK2201 - Nguyên lý máy',
                'mon_hoc_id' => 23,
                'giang_vien_id' => 20,
                'hoc_ky' => 'HK6',
                'nam_hoc' => '2025-2026',
                'si_so_toi_da' => 40,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2026-07-08 07:30:06',
                'ngay_cap_nhat' => '2026-07-08 07:30:06',
            ),
        ));
        
        
    }
}