<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class LopTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    /**
     * Convert year (e.g. 2022) to khoa_hoc string (e.g. "K22 (2022-2025)")
     */
    private function toKhoaHoc(int $year): string
    {
        $k = $year - 2000;
        return "K{$k} ({$year}-" . ($year + 3) . ")";
    }

    public function run()
    {
        // Update existing records instead of deleting them
        // This preserves foreign key relationships
        
        $data = array (
            0 => 
            array (
                'id' => 1,
                'ma_lop' => 'CNTT2201',
                'ten_lop' => 'Công nghệ Thông tin 2022-1',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-03 08:00:00',
                'ngay_cap_nhat' => '2022-09-03 08:00:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ma_lop' => 'CNTT2202',
                'ten_lop' => 'Công nghệ Thông tin 2022-2',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-14 08:00:00',
                'ngay_cap_nhat' => '2022-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ma_lop' => 'CNTT2203',
                'ten_lop' => 'Công nghệ Thông tin 2022-3',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-05 08:00:00',
                'ngay_cap_nhat' => '2022-09-05 08:00:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ma_lop' => 'CNTT2301',
                'ten_lop' => 'Công nghệ Thông tin 2023-1',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-15 08:00:00',
                'ngay_cap_nhat' => '2023-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ma_lop' => 'CNTT2302',
                'ten_lop' => 'Công nghệ Thông tin 2023-2',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-06 08:00:00',
                'ngay_cap_nhat' => '2023-09-06 08:00:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ma_lop' => 'CNTT2303',
                'ten_lop' => 'Công nghệ Thông tin 2023-3',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-02 08:00:00',
                'ngay_cap_nhat' => '2023-09-02 08:00:00',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'ma_lop' => 'CNTT2401',
                'ten_lop' => 'Công nghệ Thông tin 2024-1',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-09 08:00:00',
                'ngay_cap_nhat' => '2024-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'ma_lop' => 'CNTT2402',
                'ten_lop' => 'Công nghệ Thông tin 2024-2',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-13 08:00:00',
                'ngay_cap_nhat' => '2024-09-13 08:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'ma_lop' => 'CNTT2403',
                'ten_lop' => 'Công nghệ Thông tin 2024-3',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-11 08:00:00',
                'ngay_cap_nhat' => '2024-09-11 08:00:00',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'ma_lop' => 'CNTT2501',
                'ten_lop' => 'Công nghệ Thông tin 2025-1',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-07 08:00:00',
                'ngay_cap_nhat' => '2025-09-07 08:00:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'ma_lop' => 'CNTT2502',
                'ten_lop' => 'Công nghệ Thông tin 2025-2',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-15 08:00:00',
                'ngay_cap_nhat' => '2025-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'ma_lop' => 'CNTT2503',
                'ten_lop' => 'Công nghệ Thông tin 2025-3',
                'khoa_id' => 1,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-11 08:00:00',
                'ngay_cap_nhat' => '2025-09-11 08:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'ma_lop' => 'CK2201',
                'ten_lop' => 'Cơ khí 2022-1',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-11 08:00:00',
                'ngay_cap_nhat' => '2022-09-11 08:00:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'ma_lop' => 'CK2202',
                'ten_lop' => 'Cơ khí 2022-2',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-13 08:00:00',
                'ngay_cap_nhat' => '2022-09-13 08:00:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'ma_lop' => 'CK2301',
                'ten_lop' => 'Cơ khí 2023-1',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-09 08:00:00',
                'ngay_cap_nhat' => '2023-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'ma_lop' => 'CK2302',
                'ten_lop' => 'Cơ khí 2023-2',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-14 08:00:00',
                'ngay_cap_nhat' => '2023-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'ma_lop' => 'CK2401',
                'ten_lop' => 'Cơ khí 2024-1',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-09 08:00:00',
                'ngay_cap_nhat' => '2024-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'ma_lop' => 'CK2402',
                'ten_lop' => 'Cơ khí 2024-2',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-03 08:00:00',
                'ngay_cap_nhat' => '2024-09-03 08:00:00',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'ma_lop' => 'CK2501',
                'ten_lop' => 'Cơ khí 2025-1',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-16 08:00:00',
                'ngay_cap_nhat' => '2025-09-16 08:00:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'ma_lop' => 'CK2502',
                'ten_lop' => 'Cơ khí 2025-2',
                'khoa_id' => 2,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-01 08:00:00',
                'ngay_cap_nhat' => '2025-09-01 08:00:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'ma_lop' => 'DDT2201',
                'ten_lop' => 'Điện - Điện tử 2022-1',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-18 08:00:00',
                'ngay_cap_nhat' => '2022-09-18 08:00:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'ma_lop' => 'DDT2202',
                'ten_lop' => 'Điện - Điện tử 2022-2',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-02 08:00:00',
                'ngay_cap_nhat' => '2022-09-02 08:00:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'ma_lop' => 'DDT2203',
                'ten_lop' => 'Điện - Điện tử 2022-3',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-12 08:00:00',
                'ngay_cap_nhat' => '2022-09-12 08:00:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'ma_lop' => 'DDT2301',
                'ten_lop' => 'Điện - Điện tử 2023-1',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-08 08:00:00',
                'ngay_cap_nhat' => '2023-09-08 08:00:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'ma_lop' => 'DDT2302',
                'ten_lop' => 'Điện - Điện tử 2023-2',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-03 08:00:00',
                'ngay_cap_nhat' => '2023-09-03 08:00:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'ma_lop' => 'DDT2303',
                'ten_lop' => 'Điện - Điện tử 2023-3',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-02 08:00:00',
                'ngay_cap_nhat' => '2023-09-02 08:00:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'ma_lop' => 'DDT2401',
                'ten_lop' => 'Điện - Điện tử 2024-1',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-01 08:00:00',
                'ngay_cap_nhat' => '2024-09-01 08:00:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'ma_lop' => 'DDT2402',
                'ten_lop' => 'Điện - Điện tử 2024-2',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-08 08:00:00',
                'ngay_cap_nhat' => '2024-09-08 08:00:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'ma_lop' => 'DDT2403',
                'ten_lop' => 'Điện - Điện tử 2024-3',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-07 08:00:00',
                'ngay_cap_nhat' => '2024-09-07 08:00:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'ma_lop' => 'DDT2501',
                'ten_lop' => 'Điện - Điện tử 2025-1',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-01 08:00:00',
                'ngay_cap_nhat' => '2025-09-01 08:00:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'ma_lop' => 'DDT2502',
                'ten_lop' => 'Điện - Điện tử 2025-2',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-20 08:00:00',
                'ngay_cap_nhat' => '2025-09-20 08:00:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'ma_lop' => 'DDT2503',
                'ten_lop' => 'Điện - Điện tử 2025-3',
                'khoa_id' => 3,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-05 08:00:00',
                'ngay_cap_nhat' => '2025-09-05 08:00:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'ma_lop' => 'CKDL2201',
                'ten_lop' => 'Cơ khí Động lực 2022-1',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-08 08:00:00',
                'ngay_cap_nhat' => '2022-09-08 08:00:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'ma_lop' => 'CKDL2202',
                'ten_lop' => 'Cơ khí Động lực 2022-2',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-05 08:00:00',
                'ngay_cap_nhat' => '2022-09-05 08:00:00',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'ma_lop' => 'CKDL2301',
                'ten_lop' => 'Cơ khí Động lực 2023-1',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-16 08:00:00',
                'ngay_cap_nhat' => '2023-09-16 08:00:00',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'ma_lop' => 'CKDL2302',
                'ten_lop' => 'Cơ khí Động lực 2023-2',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-04 08:00:00',
                'ngay_cap_nhat' => '2023-09-04 08:00:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'ma_lop' => 'CKDL2401',
                'ten_lop' => 'Cơ khí Động lực 2024-1',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-19 08:00:00',
                'ngay_cap_nhat' => '2024-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'ma_lop' => 'CKDL2402',
                'ten_lop' => 'Cơ khí Động lực 2024-2',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-07 08:00:00',
                'ngay_cap_nhat' => '2024-09-07 08:00:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'ma_lop' => 'CKDL2501',
                'ten_lop' => 'Cơ khí Động lực 2025-1',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-15 08:00:00',
                'ngay_cap_nhat' => '2025-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'ma_lop' => 'CKDL2502',
                'ten_lop' => 'Cơ khí Động lực 2025-2',
                'khoa_id' => 4,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-09 08:00:00',
                'ngay_cap_nhat' => '2025-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'ma_lop' => 'KT2201',
                'ten_lop' => 'Kinh tế 2022-1',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-12 08:00:00',
                'ngay_cap_nhat' => '2022-09-12 08:00:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'ma_lop' => 'KT2202',
                'ten_lop' => 'Kinh tế 2022-2',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-06 08:00:00',
                'ngay_cap_nhat' => '2022-09-06 08:00:00',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'ma_lop' => 'KT2203',
                'ten_lop' => 'Kinh tế 2022-3',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-20 08:00:00',
                'ngay_cap_nhat' => '2022-09-20 08:00:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'ma_lop' => 'KT2301',
                'ten_lop' => 'Kinh tế 2023-1',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-20 08:00:00',
                'ngay_cap_nhat' => '2023-09-20 08:00:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'ma_lop' => 'KT2302',
                'ten_lop' => 'Kinh tế 2023-2',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-04 08:00:00',
                'ngay_cap_nhat' => '2023-09-04 08:00:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'ma_lop' => 'KT2303',
                'ten_lop' => 'Kinh tế 2023-3',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-06 08:00:00',
                'ngay_cap_nhat' => '2023-09-06 08:00:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'ma_lop' => 'KT2401',
                'ten_lop' => 'Kinh tế 2024-1',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-10 08:00:00',
                'ngay_cap_nhat' => '2024-09-10 08:00:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'ma_lop' => 'KT2402',
                'ten_lop' => 'Kinh tế 2024-2',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-04 08:00:00',
                'ngay_cap_nhat' => '2024-09-04 08:00:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'ma_lop' => 'KT2403',
                'ten_lop' => 'Kinh tế 2024-3',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-19 08:00:00',
                'ngay_cap_nhat' => '2024-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'ma_lop' => 'KT2501',
                'ten_lop' => 'Kinh tế 2025-1',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-01 08:00:00',
                'ngay_cap_nhat' => '2025-09-01 08:00:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'ma_lop' => 'KT2502',
                'ten_lop' => 'Kinh tế 2025-2',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-10 08:00:00',
                'ngay_cap_nhat' => '2025-09-10 08:00:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'ma_lop' => 'KT2503',
                'ten_lop' => 'Kinh tế 2025-3',
                'khoa_id' => 5,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-19 08:00:00',
                'ngay_cap_nhat' => '2025-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'ma_lop' => 'XD2201',
                'ten_lop' => 'Xây dựng 2022-1',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-13 08:00:00',
                'ngay_cap_nhat' => '2022-09-13 08:00:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'ma_lop' => 'XD2202',
                'ten_lop' => 'Xây dựng 2022-2',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-13 08:00:00',
                'ngay_cap_nhat' => '2022-09-13 08:00:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'ma_lop' => 'XD2301',
                'ten_lop' => 'Xây dựng 2023-1',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-07 08:00:00',
                'ngay_cap_nhat' => '2023-09-07 08:00:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'ma_lop' => 'XD2302',
                'ten_lop' => 'Xây dựng 2023-2',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-03 08:00:00',
                'ngay_cap_nhat' => '2023-09-03 08:00:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'ma_lop' => 'XD2401',
                'ten_lop' => 'Xây dựng 2024-1',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-19 08:00:00',
                'ngay_cap_nhat' => '2024-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'ma_lop' => 'XD2402',
                'ten_lop' => 'Xây dựng 2024-2',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-08 08:00:00',
                'ngay_cap_nhat' => '2024-09-08 08:00:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'ma_lop' => 'XD2501',
                'ten_lop' => 'Xây dựng 2025-1',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-04 08:00:00',
                'ngay_cap_nhat' => '2025-09-04 08:00:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'ma_lop' => 'XD2502',
                'ten_lop' => 'Xây dựng 2025-2',
                'khoa_id' => 6,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-10 08:00:00',
                'ngay_cap_nhat' => '2025-09-10 08:00:00',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'ma_lop' => 'NN2201',
                'ten_lop' => 'Ngoại ngữ 2022-1',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-20 08:00:00',
                'ngay_cap_nhat' => '2022-09-20 08:00:00',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'ma_lop' => 'NN2202',
                'ten_lop' => 'Ngoại ngữ 2022-2',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-04 08:00:00',
                'ngay_cap_nhat' => '2022-09-04 08:00:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'ma_lop' => 'NN2203',
                'ten_lop' => 'Ngoại ngữ 2022-3',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-19 08:00:00',
                'ngay_cap_nhat' => '2022-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'ma_lop' => 'NN2301',
                'ten_lop' => 'Ngoại ngữ 2023-1',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-02 08:00:00',
                'ngay_cap_nhat' => '2023-09-02 08:00:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'ma_lop' => 'NN2302',
                'ten_lop' => 'Ngoại ngữ 2023-2',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-12 08:00:00',
                'ngay_cap_nhat' => '2023-09-12 08:00:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'ma_lop' => 'NN2303',
                'ten_lop' => 'Ngoại ngữ 2023-3',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-18 08:00:00',
                'ngay_cap_nhat' => '2023-09-18 08:00:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'ma_lop' => 'NN2401',
                'ten_lop' => 'Ngoại ngữ 2024-1',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-14 08:00:00',
                'ngay_cap_nhat' => '2024-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'ma_lop' => 'NN2402',
                'ten_lop' => 'Ngoại ngữ 2024-2',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-12 08:00:00',
                'ngay_cap_nhat' => '2024-09-12 08:00:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'ma_lop' => 'NN2403',
                'ten_lop' => 'Ngoại ngữ 2024-3',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-03 08:00:00',
                'ngay_cap_nhat' => '2024-09-03 08:00:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'ma_lop' => 'NN2501',
                'ten_lop' => 'Ngoại ngữ 2025-1',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-17 08:00:00',
                'ngay_cap_nhat' => '2025-09-17 08:00:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'ma_lop' => 'NN2502',
                'ten_lop' => 'Ngoại ngữ 2025-2',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-11 08:00:00',
                'ngay_cap_nhat' => '2025-09-11 08:00:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'ma_lop' => 'NN2503',
                'ten_lop' => 'Ngoại ngữ 2025-3',
                'khoa_id' => 7,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-01 08:00:00',
                'ngay_cap_nhat' => '2025-09-01 08:00:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'ma_lop' => 'HOA2201',
                'ten_lop' => 'Công nghệ Hóa học 2022-1',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-14 08:00:00',
                'ngay_cap_nhat' => '2022-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'ma_lop' => 'HOA2202',
                'ten_lop' => 'Công nghệ Hóa học 2022-2',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-16 08:00:00',
                'ngay_cap_nhat' => '2022-09-16 08:00:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'ma_lop' => 'HOA2301',
                'ten_lop' => 'Công nghệ Hóa học 2023-1',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-04 08:00:00',
                'ngay_cap_nhat' => '2023-09-04 08:00:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'ma_lop' => 'HOA2302',
                'ten_lop' => 'Công nghệ Hóa học 2023-2',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-14 08:00:00',
                'ngay_cap_nhat' => '2023-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'ma_lop' => 'HOA2401',
                'ten_lop' => 'Công nghệ Hóa học 2024-1',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-12 08:00:00',
                'ngay_cap_nhat' => '2024-09-12 08:00:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'ma_lop' => 'HOA2402',
                'ten_lop' => 'Công nghệ Hóa học 2024-2',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-15 08:00:00',
                'ngay_cap_nhat' => '2024-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'ma_lop' => 'HOA2501',
                'ten_lop' => 'Công nghệ Hóa học 2025-1',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-05 08:00:00',
                'ngay_cap_nhat' => '2025-09-05 08:00:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'ma_lop' => 'HOA2502',
                'ten_lop' => 'Công nghệ Hóa học 2025-2',
                'khoa_id' => 8,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-14 08:00:00',
                'ngay_cap_nhat' => '2025-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'ma_lop' => 'DL2201',
                'ten_lop' => 'Du lịch - Nhà hàng 2022-1',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-06 08:00:00',
                'ngay_cap_nhat' => '2022-09-06 08:00:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'ma_lop' => 'DL2202',
                'ten_lop' => 'Du lịch - Nhà hàng 2022-2',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-17 08:00:00',
                'ngay_cap_nhat' => '2022-09-17 08:00:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'ma_lop' => 'DL2203',
                'ten_lop' => 'Du lịch - Nhà hàng 2022-3',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-09 08:00:00',
                'ngay_cap_nhat' => '2022-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'ma_lop' => 'DL2301',
                'ten_lop' => 'Du lịch - Nhà hàng 2023-1',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-20 08:00:00',
                'ngay_cap_nhat' => '2023-09-20 08:00:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'ma_lop' => 'DL2302',
                'ten_lop' => 'Du lịch - Nhà hàng 2023-2',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-18 08:00:00',
                'ngay_cap_nhat' => '2023-09-18 08:00:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'ma_lop' => 'DL2303',
                'ten_lop' => 'Du lịch - Nhà hàng 2023-3',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-16 08:00:00',
                'ngay_cap_nhat' => '2023-09-16 08:00:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'ma_lop' => 'DL2401',
                'ten_lop' => 'Du lịch - Nhà hàng 2024-1',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-15 08:00:00',
                'ngay_cap_nhat' => '2024-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'ma_lop' => 'DL2402',
                'ten_lop' => 'Du lịch - Nhà hàng 2024-2',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-14 08:00:00',
                'ngay_cap_nhat' => '2024-09-14 08:00:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'ma_lop' => 'DL2403',
                'ten_lop' => 'Du lịch - Nhà hàng 2024-3',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-19 08:00:00',
                'ngay_cap_nhat' => '2024-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'ma_lop' => 'DL2501',
                'ten_lop' => 'Du lịch - Nhà hàng 2025-1',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-09 08:00:00',
                'ngay_cap_nhat' => '2025-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'ma_lop' => 'DL2502',
                'ten_lop' => 'Du lịch - Nhà hàng 2025-2',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-11 08:00:00',
                'ngay_cap_nhat' => '2025-09-11 08:00:00',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'ma_lop' => 'DL2503',
                'ten_lop' => 'Du lịch - Nhà hàng 2025-3',
                'khoa_id' => 9,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-08 08:00:00',
                'ngay_cap_nhat' => '2025-09-08 08:00:00',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'ma_lop' => 'SP2201',
                'ten_lop' => 'Lý luận Chính trị 2022-1',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-03 08:00:00',
                'ngay_cap_nhat' => '2022-09-03 08:00:00',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'ma_lop' => 'SP2202',
                'ten_lop' => 'Lý luận Chính trị 2022-2',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2022),
                'trang_thai' => 'da_tot_nghiep',
                'ngay_tao' => '2022-09-09 08:00:00',
                'ngay_cap_nhat' => '2022-09-09 08:00:00',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'ma_lop' => 'SP2301',
                'ten_lop' => 'Lý luận Chính trị 2023-1',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-15 08:00:00',
                'ngay_cap_nhat' => '2023-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'ma_lop' => 'SP2302',
                'ten_lop' => 'Lý luận Chính trị 2023-2',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2023),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2023-09-08 08:00:00',
                'ngay_cap_nhat' => '2023-09-08 08:00:00',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'ma_lop' => 'SP2401',
                'ten_lop' => 'Lý luận Chính trị 2024-1',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-15 08:00:00',
                'ngay_cap_nhat' => '2024-09-15 08:00:00',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'ma_lop' => 'SP2402',
                'ten_lop' => 'Lý luận Chính trị 2024-2',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2024),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2024-09-19 08:00:00',
                'ngay_cap_nhat' => '2024-09-19 08:00:00',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'ma_lop' => 'SP2501',
                'ten_lop' => 'Lý luận Chính trị 2025-1',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-20 08:00:00',
                'ngay_cap_nhat' => '2025-09-20 08:00:00',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'ma_lop' => 'SP2502',
                'ten_lop' => 'Lý luận Chính trị 2025-2',
                'khoa_id' => 10,
                'khoa_hoc' => $this->toKhoaHoc(2025),
                'trang_thai' => 'dang_hoc',
                'ngay_tao' => '2025-09-13 08:00:00',
                'ngay_cap_nhat' => '2025-09-13 08:00:00',
                'deleted_at' => NULL,
            ),
        );
        
        // Use upsert to update existing records or insert new ones
        foreach ($data as $record) {
            \DB::table('lop')->updateOrInsert(
                ['id' => $record['id']],
                $record
            );
        }
    }
}