<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MonHocTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('mon_hoc')->delete();
        
        \DB::table('mon_hoc')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ma_mon' => 'MH01001',
                'ten_mon' => 'Lập trình căn bản C',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-08-01 20:25:00',
                'ngay_cap_nhat' => '2024-08-01 20:25:00',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'ma_mon' => 'MH01002',
                'ten_mon' => 'Cấu trúc dữ liệu và giải thuật',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-02-02 04:56:00',
                'ngay_cap_nhat' => '2025-02-02 04:56:00',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'ma_mon' => 'MH01003',
                'ten_mon' => 'Lập trình hướng đối tượng Java',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-11-23 22:56:00',
                'ngay_cap_nhat' => '2025-11-23 22:56:00',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'ma_mon' => 'MH01004',
                'ten_mon' => 'Cơ sở dữ liệu',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-28 14:15:00',
                'ngay_cap_nhat' => '2025-03-28 14:15:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'ma_mon' => 'MH01005',
                'ten_mon' => 'Lập trình Web với PHP',
                'tin_chi' => 4,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-12 04:25:00',
                'ngay_cap_nhat' => '2025-09-12 04:25:00',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'ma_mon' => 'MH01006',
                'ten_mon' => 'Lập trình Web với Laravel',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-11-19 02:31:00',
                'ngay_cap_nhat' => '2024-11-19 02:31:00',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'ma_mon' => 'MH01007',
                'ten_mon' => 'Phát triển ứng dụng di động Android',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-20 14:40:00',
                'ngay_cap_nhat' => '2024-10-20 14:40:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'ma_mon' => 'MH01008',
                'ten_mon' => 'Mạng máy tính',
                'tin_chi' => 4,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-06 05:04:00',
                'ngay_cap_nhat' => '2025-09-06 05:04:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'ma_mon' => 'MH01009',
                'ten_mon' => 'An toàn thông tin',
                'tin_chi' => 3,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-23 02:16:00',
                'ngay_cap_nhat' => '2025-10-23 02:16:00',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'ma_mon' => 'MH01010',
                'ten_mon' => 'Hệ điều hành Linux',
                'tin_chi' => 4,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-26 07:56:00',
                'ngay_cap_nhat' => '2024-10-26 07:56:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'ma_mon' => 'MH01011',
                'ten_mon' => 'Lập trình Python',
                'tin_chi' => 4,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-06-13 13:18:00',
                'ngay_cap_nhat' => '2025-06-13 13:18:00',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'ma_mon' => 'MH01012',
                'ten_mon' => 'Trí tuệ nhân tạo căn bản',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-07 10:46:00',
                'ngay_cap_nhat' => '2025-10-07 10:46:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'ma_mon' => 'MH01013',
                'ten_mon' => 'Phân tích thiết kế hệ thống',
                'tin_chi' => 3,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-30 02:58:00',
                'ngay_cap_nhat' => '2024-12-30 02:58:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'ma_mon' => 'MH01014',
                'ten_mon' => 'Kiểm thử phần mềm',
                'tin_chi' => 4,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-02 06:32:00',
                'ngay_cap_nhat' => '2025-05-02 06:32:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'ma_mon' => 'MH01015',
                'ten_mon' => 'Lập trình JavaScript & Node.js',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-07-17 15:34:00',
                'ngay_cap_nhat' => '2025-07-17 15:34:00',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'ma_mon' => 'MH01016',
                'ten_mon' => 'Quản trị mạng Windows Server',
                'tin_chi' => 3,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-28 01:01:00',
                'ngay_cap_nhat' => '2025-05-28 01:01:00',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'ma_mon' => 'MH01017',
                'ten_mon' => 'Lập trình Frontend với React',
                'tin_chi' => 3,
                'khoa_id' => 1,
                'bo_mon_id' => 1,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-10 17:03:00',
                'ngay_cap_nhat' => '2025-05-10 17:03:00',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'ma_mon' => 'MH01018',
                'ten_mon' => 'Cơ sở dữ liệu nâng cao SQL Server',
                'tin_chi' => 3,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-18 12:46:00',
                'ngay_cap_nhat' => '2024-09-18 12:46:00',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'ma_mon' => 'MH01019',
                'ten_mon' => 'Nhập môn ngành CNTT',
                'tin_chi' => 2,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-11-05 14:42:00',
                'ngay_cap_nhat' => '2024-11-05 14:42:00',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'ma_mon' => 'MH01020',
                'ten_mon' => 'Đồ án chuyên ngành CNTT',
                'tin_chi' => 3,
                'khoa_id' => 1,
                'bo_mon_id' => 2,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-16 18:33:00',
                'ngay_cap_nhat' => '2024-12-16 18:33:00',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'ma_mon' => 'MH02021',
                'ten_mon' => 'Vẽ kỹ thuật cơ khí',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-22 08:19:00',
                'ngay_cap_nhat' => '2025-01-22 08:19:00',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'ma_mon' => 'MH02022',
                'ten_mon' => 'Cơ học kỹ thuật',
                'tin_chi' => 4,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-07-18 00:57:00',
                'ngay_cap_nhat' => '2025-07-18 00:57:00',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'ma_mon' => 'MH02023',
                'ten_mon' => 'Nguyên lý máy',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-10 17:04:00',
                'ngay_cap_nhat' => '2025-03-10 17:04:00',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'ma_mon' => 'MH02024',
                'ten_mon' => 'Chi tiết máy',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 3,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-02-21 04:14:00',
                'ngay_cap_nhat' => '2025-02-21 04:14:00',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'ma_mon' => 'MH02025',
                'ten_mon' => 'Công nghệ chế tạo máy',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 3,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-08-29 17:04:00',
                'ngay_cap_nhat' => '2024-08-29 17:04:00',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'ma_mon' => 'MH02026',
                'ten_mon' => 'Gia công CNC',
                'tin_chi' => 3,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-11 02:15:00',
                'ngay_cap_nhat' => '2024-09-11 02:15:00',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'ma_mon' => 'MH02027',
                'ten_mon' => 'Vật liệu học',
                'tin_chi' => 4,
                'khoa_id' => 2,
                'bo_mon_id' => 3,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-11-09 16:34:00',
                'ngay_cap_nhat' => '2025-11-09 16:34:00',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'ma_mon' => 'MH02028',
                'ten_mon' => 'Dung sai kỹ thuật đo',
                'tin_chi' => 4,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-27 17:50:00',
                'ngay_cap_nhat' => '2025-10-27 17:50:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'ma_mon' => 'MH02029',
                'ten_mon' => 'Autocad cơ khí',
                'tin_chi' => 3,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-10 13:06:00',
                'ngay_cap_nhat' => '2025-01-10 13:06:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'ma_mon' => 'MH02030',
                'ten_mon' => 'SolidWorks 3D',
                'tin_chi' => 3,
                'khoa_id' => 2,
                'bo_mon_id' => 3,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-06 23:29:00',
                'ngay_cap_nhat' => '2025-09-06 23:29:00',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'ma_mon' => 'MH02031',
                'ten_mon' => 'Đồ án công nghệ chế tạo máy',
                'tin_chi' => 4,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-08 11:25:00',
                'ngay_cap_nhat' => '2024-10-08 11:25:00',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'ma_mon' => 'MH02032',
                'ten_mon' => 'Kỹ thuật hàn',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-11 16:12:00',
                'ngay_cap_nhat' => '2025-03-11 16:12:00',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'ma_mon' => 'MH02033',
                'ten_mon' => 'Sức bền vật liệu',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 4,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-05 15:17:00',
                'ngay_cap_nhat' => '2025-09-05 15:17:00',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'ma_mon' => 'MH02034',
                'ten_mon' => 'Máy công cụ',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 3,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-16 00:51:00',
                'ngay_cap_nhat' => '2024-09-16 00:51:00',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'ma_mon' => 'MH02035',
                'ten_mon' => 'Thiết kế khuôn mẫu',
                'tin_chi' => 2,
                'khoa_id' => 2,
                'bo_mon_id' => 3,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-15 12:59:00',
                'ngay_cap_nhat' => '2024-07-15 12:59:00',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'ma_mon' => 'MH03036',
                'ten_mon' => 'Mạch điện',
                'tin_chi' => 2,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-21 01:30:00',
                'ngay_cap_nhat' => '2025-08-21 01:30:00',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'ma_mon' => 'MH03037',
                'ten_mon' => 'Kỹ thuật điện tử cơ bản',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-08-29 15:24:00',
                'ngay_cap_nhat' => '2024-08-29 15:24:00',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'ma_mon' => 'MH03038',
                'ten_mon' => 'Đo lường điện',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-29 00:18:00',
                'ngay_cap_nhat' => '2025-03-29 00:18:00',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'ma_mon' => 'MH03039',
                'ten_mon' => 'Truyền động điện',
                'tin_chi' => 4,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-11-10 14:12:00',
                'ngay_cap_nhat' => '2025-11-10 14:12:00',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'ma_mon' => 'MH03040',
                'ten_mon' => 'Khí cụ điện',
                'tin_chi' => 2,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-08-29 04:47:00',
                'ngay_cap_nhat' => '2024-08-29 04:47:00',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'ma_mon' => 'MH03041',
                'ten_mon' => 'PLC cơ bản',
                'tin_chi' => 4,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-17 11:03:00',
                'ngay_cap_nhat' => '2025-05-17 11:03:00',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'ma_mon' => 'MH03042',
                'ten_mon' => 'Vi xử lý - Vi điều khiển',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-08 11:32:00',
                'ngay_cap_nhat' => '2024-12-08 11:32:00',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'ma_mon' => 'MH03043',
                'ten_mon' => 'Hệ thống cung cấp điện',
                'tin_chi' => 2,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-09 05:04:00',
                'ngay_cap_nhat' => '2024-09-09 05:04:00',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'ma_mon' => 'MH03044',
                'ten_mon' => 'Điện tử công suất',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-31 04:15:00',
                'ngay_cap_nhat' => '2024-10-31 04:15:00',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'ma_mon' => 'MH03045',
                'ten_mon' => 'Kỹ thuật số',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-21 23:42:00',
                'ngay_cap_nhat' => '2024-09-21 23:42:00',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'ma_mon' => 'MH03046',
                'ten_mon' => 'Truyền thông không dây',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-26 07:45:00',
                'ngay_cap_nhat' => '2025-01-26 07:45:00',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'ma_mon' => 'MH03047',
                'ten_mon' => 'Mạng viễn thông',
                'tin_chi' => 2,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-28 22:08:00',
                'ngay_cap_nhat' => '2025-03-28 22:08:00',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'ma_mon' => 'MH03048',
                'ten_mon' => 'Thiết kế mạch điện tử',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 6,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-19 12:00:00',
                'ngay_cap_nhat' => '2025-05-19 12:00:00',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'ma_mon' => 'MH03049',
                'ten_mon' => 'Đồ án điện tử viễn thông',
                'tin_chi' => 3,
                'khoa_id' => 3,
                'bo_mon_id' => 5,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-10 12:34:00',
                'ngay_cap_nhat' => '2024-10-10 12:34:00',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'ma_mon' => 'MH04050',
                'ten_mon' => 'Động cơ đốt trong',
                'tin_chi' => 3,
                'khoa_id' => 4,
                'bo_mon_id' => 8,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-28 14:59:00',
                'ngay_cap_nhat' => '2025-03-28 14:59:00',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'ma_mon' => 'MH04051',
                'ten_mon' => 'Hệ thống điện thân xe',
                'tin_chi' => 2,
                'khoa_id' => 4,
                'bo_mon_id' => 7,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-07 21:18:00',
                'ngay_cap_nhat' => '2025-03-07 21:18:00',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'ma_mon' => 'MH04052',
                'ten_mon' => 'Khung gầm ô tô',
                'tin_chi' => 3,
                'khoa_id' => 4,
                'bo_mon_id' => 7,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-06 05:51:00',
                'ngay_cap_nhat' => '2025-05-06 05:51:00',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'ma_mon' => 'MH04053',
                'ten_mon' => 'Kỹ thuật sửa chữa ô tô',
                'tin_chi' => 4,
                'khoa_id' => 4,
                'bo_mon_id' => 7,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-03 07:06:00',
                'ngay_cap_nhat' => '2025-05-03 07:06:00',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'ma_mon' => 'MH04054',
                'ten_mon' => 'Chẩn đoán hư hỏng ô tô',
                'tin_chi' => 3,
                'khoa_id' => 4,
                'bo_mon_id' => 7,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-26 13:47:00',
                'ngay_cap_nhat' => '2024-10-26 13:47:00',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'ma_mon' => 'MH04055',
                'ten_mon' => 'Cơ điện tử ô tô',
                'tin_chi' => 3,
                'khoa_id' => 4,
                'bo_mon_id' => 8,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-04-15 05:13:00',
                'ngay_cap_nhat' => '2025-04-15 05:13:00',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'ma_mon' => 'MH04056',
                'ten_mon' => 'Hệ thống truyền lực ô tô',
                'tin_chi' => 2,
                'khoa_id' => 4,
                'bo_mon_id' => 8,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-28 02:31:00',
                'ngay_cap_nhat' => '2025-03-28 02:31:00',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'ma_mon' => 'MH04057',
                'ten_mon' => 'Công nghệ ô tô hybrid',
                'tin_chi' => 2,
                'khoa_id' => 4,
                'bo_mon_id' => 8,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-03 06:27:00',
                'ngay_cap_nhat' => '2024-10-03 06:27:00',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'ma_mon' => 'MH04058',
                'ten_mon' => 'Thực hành động cơ xăng',
                'tin_chi' => 2,
                'khoa_id' => 4,
                'bo_mon_id' => 7,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-03 20:49:00',
                'ngay_cap_nhat' => '2024-07-03 20:49:00',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'ma_mon' => 'MH04059',
                'ten_mon' => 'Thực hành động cơ diesel',
                'tin_chi' => 4,
                'khoa_id' => 4,
                'bo_mon_id' => 8,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-25 15:47:00',
                'ngay_cap_nhat' => '2025-03-25 15:47:00',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'ma_mon' => 'MH05060',
                'ten_mon' => 'Nguyên lý kế toán',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 9,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-11 03:00:00',
                'ngay_cap_nhat' => '2025-09-11 03:00:00',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'ma_mon' => 'MH05061',
                'ten_mon' => 'Kế toán tài chính doanh nghiệp',
                'tin_chi' => 2,
                'khoa_id' => 5,
                'bo_mon_id' => 10,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-11-30 03:02:00',
                'ngay_cap_nhat' => '2024-11-30 03:02:00',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'ma_mon' => 'MH05062',
                'ten_mon' => 'Kế toán thuế',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 9,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-11-28 23:08:00',
                'ngay_cap_nhat' => '2024-11-28 23:08:00',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'ma_mon' => 'MH05063',
                'ten_mon' => 'Nguyên lý thống kê',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 10,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-07-08 11:57:00',
                'ngay_cap_nhat' => '2025-07-08 11:57:00',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'ma_mon' => 'MH05064',
                'ten_mon' => 'Quản trị học',
                'tin_chi' => 2,
                'khoa_id' => 5,
                'bo_mon_id' => 10,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-13 07:06:00',
                'ngay_cap_nhat' => '2025-03-13 07:06:00',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'ma_mon' => 'MH05065',
                'ten_mon' => 'Marketing căn bản',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 9,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-21 05:47:00',
                'ngay_cap_nhat' => '2025-08-21 05:47:00',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'ma_mon' => 'MH05066',
                'ten_mon' => 'Tài chính doanh nghiệp',
                'tin_chi' => 2,
                'khoa_id' => 5,
                'bo_mon_id' => 10,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-13 15:56:00',
                'ngay_cap_nhat' => '2024-12-13 15:56:00',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'ma_mon' => 'MH05067',
                'ten_mon' => 'Kiểm toán căn bản',
                'tin_chi' => 2,
                'khoa_id' => 5,
                'bo_mon_id' => 10,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-31 09:59:00',
                'ngay_cap_nhat' => '2024-12-31 09:59:00',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'ma_mon' => 'MH05068',
                'ten_mon' => 'Quản trị nhân sự',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 9,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-11 18:10:00',
                'ngay_cap_nhat' => '2025-03-11 18:10:00',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'ma_mon' => 'MH05069',
                'ten_mon' => 'Thương mại điện tử',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 9,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-08-09 01:14:00',
                'ngay_cap_nhat' => '2024-08-09 01:14:00',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'ma_mon' => 'MH05070',
                'ten_mon' => 'Phân tích báo cáo tài chính',
                'tin_chi' => 3,
                'khoa_id' => 5,
                'bo_mon_id' => 9,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-06-23 19:52:00',
                'ngay_cap_nhat' => '2025-06-23 19:52:00',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'ma_mon' => 'MH05071',
                'ten_mon' => 'Khởi nghiệp kinh doanh',
                'tin_chi' => 2,
                'khoa_id' => 5,
                'bo_mon_id' => 10,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-25 07:12:00',
                'ngay_cap_nhat' => '2024-07-25 07:12:00',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'ma_mon' => 'MH06072',
                'ten_mon' => 'Trắc địa căn bản',
                'tin_chi' => 3,
                'khoa_id' => 6,
                'bo_mon_id' => 12,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-04-11 12:49:00',
                'ngay_cap_nhat' => '2025-04-11 12:49:00',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'ma_mon' => 'MH06073',
                'ten_mon' => 'Cơ học đất',
                'tin_chi' => 3,
                'khoa_id' => 6,
                'bo_mon_id' => 12,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-12-03 22:43:00',
                'ngay_cap_nhat' => '2025-12-03 22:43:00',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'ma_mon' => 'MH06074',
                'ten_mon' => 'Kết cấu công trình',
                'tin_chi' => 2,
                'khoa_id' => 6,
                'bo_mon_id' => 12,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-26 18:11:00',
                'ngay_cap_nhat' => '2024-10-26 18:11:00',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'ma_mon' => 'MH06075',
                'ten_mon' => 'Vật liệu xây dựng',
                'tin_chi' => 2,
                'khoa_id' => 6,
                'bo_mon_id' => 12,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-10-20 05:27:00',
                'ngay_cap_nhat' => '2024-10-20 05:27:00',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'ma_mon' => 'MH06076',
                'ten_mon' => 'Kỹ thuật thi công',
                'tin_chi' => 4,
                'khoa_id' => 6,
                'bo_mon_id' => 11,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-17 23:38:00',
                'ngay_cap_nhat' => '2025-05-17 23:38:00',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'ma_mon' => 'MH06077',
                'ten_mon' => 'Dự toán xây dựng',
                'tin_chi' => 3,
                'khoa_id' => 6,
                'bo_mon_id' => 12,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-10 18:02:00',
                'ngay_cap_nhat' => '2025-01-10 18:02:00',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'ma_mon' => 'MH06078',
                'ten_mon' => 'Nền và móng',
                'tin_chi' => 2,
                'khoa_id' => 6,
                'bo_mon_id' => 11,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-01-17 21:27:00',
                'ngay_cap_nhat' => '2025-01-17 21:27:00',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'ma_mon' => 'MH06079',
                'ten_mon' => 'Autocad xây dựng',
                'tin_chi' => 4,
                'khoa_id' => 6,
                'bo_mon_id' => 11,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-06-04 05:20:00',
                'ngay_cap_nhat' => '2025-06-04 05:20:00',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'ma_mon' => 'MH06080',
                'ten_mon' => 'Đồ án kết cấu bê tông',
                'tin_chi' => 4,
                'khoa_id' => 6,
                'bo_mon_id' => 12,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-04 02:19:00',
                'ngay_cap_nhat' => '2025-05-04 02:19:00',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'ma_mon' => 'MH07081',
                'ten_mon' => 'Anh văn căn bản 1',
                'tin_chi' => 3,
                'khoa_id' => 7,
                'bo_mon_id' => 13,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-17 08:18:00',
                'ngay_cap_nhat' => '2025-08-17 08:18:00',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'ma_mon' => 'MH07082',
                'ten_mon' => 'Anh văn căn bản 2',
                'tin_chi' => 2,
                'khoa_id' => 7,
                'bo_mon_id' => 13,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-04 07:24:00',
                'ngay_cap_nhat' => '2025-09-04 07:24:00',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'ma_mon' => 'MH07083',
                'ten_mon' => 'Anh văn giao tiếp',
                'tin_chi' => 3,
                'khoa_id' => 7,
                'bo_mon_id' => 13,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-04 22:35:00',
                'ngay_cap_nhat' => '2025-05-04 22:35:00',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'ma_mon' => 'MH07084',
                'ten_mon' => 'Anh văn chuyên ngành kỹ thuật',
                'tin_chi' => 3,
                'khoa_id' => 7,
                'bo_mon_id' => 14,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-04-19 16:27:00',
                'ngay_cap_nhat' => '2025-04-19 16:27:00',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'ma_mon' => 'MH07085',
                'ten_mon' => 'Nhật văn cơ sở 1',
                'tin_chi' => 3,
                'khoa_id' => 7,
                'bo_mon_id' => 13,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-26 00:43:00',
                'ngay_cap_nhat' => '2025-09-26 00:43:00',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'ma_mon' => 'MH07086',
                'ten_mon' => 'Nhật văn cơ sở 2',
                'tin_chi' => 3,
                'khoa_id' => 7,
                'bo_mon_id' => 13,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-28 09:10:00',
                'ngay_cap_nhat' => '2025-10-28 09:10:00',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'ma_mon' => 'MH07087',
                'ten_mon' => 'Kỹ năng nghe nói tiếng Anh',
                'tin_chi' => 3,
                'khoa_id' => 7,
                'bo_mon_id' => 14,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-12-10 07:40:00',
                'ngay_cap_nhat' => '2025-12-10 07:40:00',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'ma_mon' => 'MH07088',
                'ten_mon' => 'Biên dịch Anh - Việt',
                'tin_chi' => 2,
                'khoa_id' => 7,
                'bo_mon_id' => 13,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-02-26 07:19:00',
                'ngay_cap_nhat' => '2025-02-26 07:19:00',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'ma_mon' => 'MH08089',
                'ten_mon' => 'Hóa phân tích đại cương',
                'tin_chi' => 2,
                'khoa_id' => 8,
                'bo_mon_id' => 15,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-11-27 10:02:00',
                'ngay_cap_nhat' => '2024-11-27 10:02:00',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'ma_mon' => 'MH08090',
                'ten_mon' => 'Hóa hữu cơ',
                'tin_chi' => 3,
                'khoa_id' => 8,
                'bo_mon_id' => 15,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-13 00:26:00',
                'ngay_cap_nhat' => '2024-09-13 00:26:00',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'ma_mon' => 'MH08091',
                'ten_mon' => 'Hóa vô cơ',
                'tin_chi' => 4,
                'khoa_id' => 8,
                'bo_mon_id' => 15,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-07-29 01:25:00',
                'ngay_cap_nhat' => '2025-07-29 01:25:00',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'ma_mon' => 'MH08092',
                'ten_mon' => 'Công nghệ xử lý nước thải',
                'tin_chi' => 2,
                'khoa_id' => 8,
                'bo_mon_id' => 16,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-05 13:49:00',
                'ngay_cap_nhat' => '2024-07-05 13:49:00',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'ma_mon' => 'MH08093',
                'ten_mon' => 'Kỹ thuật phân tích thí nghiệm',
                'tin_chi' => 2,
                'khoa_id' => 8,
                'bo_mon_id' => 16,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-28 08:33:00',
                'ngay_cap_nhat' => '2024-12-28 08:33:00',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'ma_mon' => 'MH08094',
                'ten_mon' => 'Hóa lý',
                'tin_chi' => 2,
                'khoa_id' => 8,
                'bo_mon_id' => 15,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-12 13:29:00',
                'ngay_cap_nhat' => '2025-03-12 13:29:00',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'ma_mon' => 'MH08095',
                'ten_mon' => 'Công nghệ vật liệu polymer',
                'tin_chi' => 3,
                'khoa_id' => 8,
                'bo_mon_id' => 16,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-05-21 00:39:00',
                'ngay_cap_nhat' => '2025-05-21 00:39:00',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'ma_mon' => 'MH09096',
                'ten_mon' => 'Nghiệp vụ lễ tân',
                'tin_chi' => 3,
                'khoa_id' => 9,
                'bo_mon_id' => 18,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-09-29 15:47:00',
                'ngay_cap_nhat' => '2025-09-29 15:47:00',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'ma_mon' => 'MH09097',
                'ten_mon' => 'Nghiệp vụ nhà hàng',
                'tin_chi' => 3,
                'khoa_id' => 9,
                'bo_mon_id' => 18,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-03-22 17:53:00',
                'ngay_cap_nhat' => '2025-03-22 17:53:00',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'ma_mon' => 'MH09098',
                'ten_mon' => 'Nghiệp vụ buồng phòng',
                'tin_chi' => 3,
                'khoa_id' => 9,
                'bo_mon_id' => 18,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-11-09 06:15:00',
                'ngay_cap_nhat' => '2025-11-09 06:15:00',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'ma_mon' => 'MH09099',
                'ten_mon' => 'Quản trị khách sạn',
                'tin_chi' => 3,
                'khoa_id' => 9,
                'bo_mon_id' => 17,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-09-18 08:18:00',
                'ngay_cap_nhat' => '2024-09-18 08:18:00',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'ma_mon' => 'MH09100',
                'ten_mon' => 'Kỹ năng phục vụ bàn',
                'tin_chi' => 3,
                'khoa_id' => 9,
                'bo_mon_id' => 17,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-06-08 20:57:00',
                'ngay_cap_nhat' => '2025-06-08 20:57:00',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'ma_mon' => 'MH09101',
                'ten_mon' => 'Văn hóa du lịch',
                'tin_chi' => 2,
                'khoa_id' => 9,
                'bo_mon_id' => 17,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-01 17:24:00',
                'ngay_cap_nhat' => '2024-12-01 17:24:00',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'ma_mon' => 'MH09102',
                'ten_mon' => 'Tổ chức sự kiện',
                'tin_chi' => 4,
                'khoa_id' => 9,
                'bo_mon_id' => 18,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-02-04 12:26:00',
                'ngay_cap_nhat' => '2025-02-04 12:26:00',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'ma_mon' => 'MH09103',
                'ten_mon' => 'Tâm lý khách du lịch',
                'tin_chi' => 3,
                'khoa_id' => 9,
                'bo_mon_id' => 17,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-10-20 23:03:00',
                'ngay_cap_nhat' => '2025-10-20 23:03:00',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'ma_mon' => 'MH10104',
                'ten_mon' => 'Triết học Mác - Lênin',
                'tin_chi' => 3,
                'khoa_id' => 10,
                'bo_mon_id' => 19,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-03 04:44:00',
                'ngay_cap_nhat' => '2025-08-03 04:44:00',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'ma_mon' => 'MH10105',
                'ten_mon' => 'Kinh tế chính trị Mác - Lênin',
                'tin_chi' => 3,
                'khoa_id' => 10,
                'bo_mon_id' => 20,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-07-25 01:00:00',
                'ngay_cap_nhat' => '2025-07-25 01:00:00',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'ma_mon' => 'MH10106',
                'ten_mon' => 'Tư tưởng Hồ Chí Minh',
                'tin_chi' => 3,
                'khoa_id' => 10,
                'bo_mon_id' => 19,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-03 23:34:00',
                'ngay_cap_nhat' => '2025-08-03 23:34:00',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'ma_mon' => 'MH10107',
                'ten_mon' => 'Pháp luật đại cương',
                'tin_chi' => 3,
                'khoa_id' => 10,
                'bo_mon_id' => 20,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-02-09 18:27:00',
                'ngay_cap_nhat' => '2025-02-09 18:27:00',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'ma_mon' => 'MH10108',
                'ten_mon' => 'Giáo dục thể chất 1',
                'tin_chi' => 2,
                'khoa_id' => 10,
                'bo_mon_id' => 20,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2025-08-02 20:42:00',
                'ngay_cap_nhat' => '2025-08-02 20:42:00',
                'deleted_at' => NULL,
            ),
            108 => 
            array (
                'id' => 109,
                'ma_mon' => 'MH10109',
                'ten_mon' => 'Giáo dục thể chất 2',
                'tin_chi' => 4,
                'khoa_id' => 10,
                'bo_mon_id' => 19,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-12-17 00:58:00',
                'ngay_cap_nhat' => '2024-12-17 00:58:00',
                'deleted_at' => NULL,
            ),
            109 => 
            array (
                'id' => 110,
                'ma_mon' => 'MH10110',
                'ten_mon' => 'Giáo dục quốc phòng - an ninh',
                'tin_chi' => 3,
                'khoa_id' => 10,
                'bo_mon_id' => 19,
                'trang_thai' => 'dang_mo',
                'ngay_tao' => '2024-07-27 22:37:00',
                'ngay_cap_nhat' => '2024-07-27 22:37:00',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}