<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TaiLieuTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tai_lieu')->delete();
        
        \DB::table('tai_lieu')->insert(array (
            0 => 
            array (
                'id' => 1,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_549449.docx',
                'lop_hoc_phan_id' => 1,
                'nguoi_tao_id' => 14,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-12-04 12:30:00',
                'ngay_cap_nhat' => '2024-12-04 12:30:00',
            ),
            1 => 
            array (
                'id' => 2,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_769399.zip',
                'lop_hoc_phan_id' => 1,
                'nguoi_tao_id' => 14,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-06-11 17:16:00',
                'ngay_cap_nhat' => '2026-06-11 17:16:00',
            ),
            2 => 
            array (
                'id' => 3,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_981610.docx',
                'lop_hoc_phan_id' => 2,
                'nguoi_tao_id' => 9,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-29 20:01:00',
                'ngay_cap_nhat' => '2024-06-29 20:01:00',
            ),
            3 => 
            array (
                'id' => 4,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_438746.docx',
                'lop_hoc_phan_id' => 2,
                'nguoi_tao_id' => 9,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-19 23:42:00',
                'ngay_cap_nhat' => '2026-05-19 23:42:00',
            ),
            4 => 
            array (
                'id' => 5,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_863094.docx',
                'lop_hoc_phan_id' => 3,
                'nguoi_tao_id' => 15,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-01 22:34:00',
                'ngay_cap_nhat' => '2026-03-01 22:34:00',
            ),
            5 => 
            array (
                'id' => 6,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_374721.docx',
                'lop_hoc_phan_id' => 4,
                'nguoi_tao_id' => 4,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-23 09:42:00',
                'ngay_cap_nhat' => '2024-11-23 09:42:00',
            ),
            6 => 
            array (
                'id' => 7,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_930489.pptx',
                'lop_hoc_phan_id' => 5,
                'nguoi_tao_id' => 18,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-12-15 08:25:00',
                'ngay_cap_nhat' => '2025-12-15 08:25:00',
            ),
            7 => 
            array (
                'id' => 8,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_575745.pdf',
                'lop_hoc_phan_id' => 6,
                'nguoi_tao_id' => 19,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-02 13:09:00',
                'ngay_cap_nhat' => '2025-04-02 13:09:00',
            ),
            8 => 
            array (
                'id' => 9,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_198685.pdf',
                'lop_hoc_phan_id' => 6,
                'nguoi_tao_id' => 19,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-05-14 03:36:00',
                'ngay_cap_nhat' => '2025-05-14 03:36:00',
            ),
            9 => 
            array (
                'id' => 10,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_815339.pptx',
                'lop_hoc_phan_id' => 7,
                'nguoi_tao_id' => 6,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-06 20:41:00',
                'ngay_cap_nhat' => '2024-03-06 20:41:00',
            ),
            10 => 
            array (
                'id' => 11,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_487040.jpg',
                'lop_hoc_phan_id' => 7,
                'nguoi_tao_id' => 6,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-29 04:29:00',
                'ngay_cap_nhat' => '2025-01-29 04:29:00',
            ),
            11 => 
            array (
                'id' => 12,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_147652.docx',
                'lop_hoc_phan_id' => 8,
                'nguoi_tao_id' => 11,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-07-12 11:32:00',
                'ngay_cap_nhat' => '2024-07-12 11:32:00',
            ),
            12 => 
            array (
                'id' => 13,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_308252.pptx',
                'lop_hoc_phan_id' => 8,
                'nguoi_tao_id' => 11,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-01-24 16:24:00',
                'ngay_cap_nhat' => '2026-01-24 16:24:00',
            ),
            13 => 
            array (
                'id' => 14,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_244935.jpg',
                'lop_hoc_phan_id' => 9,
                'nguoi_tao_id' => 20,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-26 20:46:00',
                'ngay_cap_nhat' => '2025-01-26 20:46:00',
            ),
            14 => 
            array (
                'id' => 15,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_954222.jpg',
                'lop_hoc_phan_id' => 10,
                'nguoi_tao_id' => 5,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-12 21:19:00',
                'ngay_cap_nhat' => '2024-11-12 21:19:00',
            ),
            15 => 
            array (
                'id' => 16,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_955216.xlsx',
                'lop_hoc_phan_id' => 10,
                'nguoi_tao_id' => 5,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-06-09 20:30:00',
                'ngay_cap_nhat' => '2026-06-09 20:30:00',
            ),
            16 => 
            array (
                'id' => 17,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_829937.xlsx',
                'lop_hoc_phan_id' => 11,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-09-12 22:59:00',
                'ngay_cap_nhat' => '2025-09-12 22:59:00',
            ),
            17 => 
            array (
                'id' => 18,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_378293.xlsx',
                'lop_hoc_phan_id' => 11,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-01-15 10:37:00',
                'ngay_cap_nhat' => '2026-01-15 10:37:00',
            ),
            18 => 
            array (
                'id' => 19,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_955216.xlsx',
                'lop_hoc_phan_id' => 12,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-18 00:54:00',
                'ngay_cap_nhat' => '2024-03-18 00:54:00',
            ),
            19 => 
            array (
                'id' => 20,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_168492.zip',
                'lop_hoc_phan_id' => 12,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-05-09 21:06:00',
                'ngay_cap_nhat' => '2024-05-09 21:06:00',
            ),
            20 => 
            array (
                'id' => 21,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_167603.xlsx',
                'lop_hoc_phan_id' => 13,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-20 07:49:00',
                'ngay_cap_nhat' => '2026-03-20 07:49:00',
            ),
            21 => 
            array (
                'id' => 22,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_229054.pptx',
                'lop_hoc_phan_id' => 13,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-07-28 23:57:00',
                'ngay_cap_nhat' => '2024-07-28 23:57:00',
            ),
            22 => 
            array (
                'id' => 23,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_486547.docx',
                'lop_hoc_phan_id' => 14,
                'nguoi_tao_id' => 26,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-04-04 19:16:00',
                'ngay_cap_nhat' => '2024-04-04 19:16:00',
            ),
            23 => 
            array (
                'id' => 24,
                'tieu_de' => 'Slide bài giảng chương 2',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_963408.pdf',
                'lop_hoc_phan_id' => 14,
                'nguoi_tao_id' => 26,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-06-17 23:04:00',
                'ngay_cap_nhat' => '2026-06-17 23:04:00',
            ),
            24 => 
            array (
                'id' => 25,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_842658.docx',
                'lop_hoc_phan_id' => 15,
                'nguoi_tao_id' => 23,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-07-28 10:06:00',
                'ngay_cap_nhat' => '2024-07-28 10:06:00',
            ),
            25 => 
            array (
                'id' => 26,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_329242.pdf',
                'lop_hoc_phan_id' => 15,
                'nguoi_tao_id' => 23,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-16 20:36:00',
                'ngay_cap_nhat' => '2024-06-16 20:36:00',
            ),
            26 => 
            array (
                'id' => 27,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_527070.pdf',
                'lop_hoc_phan_id' => 16,
                'nguoi_tao_id' => 28,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-06-17 14:43:00',
                'ngay_cap_nhat' => '2025-06-17 14:43:00',
            ),
            27 => 
            array (
                'id' => 28,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_773662.docx',
                'lop_hoc_phan_id' => 17,
                'nguoi_tao_id' => 23,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-01 05:27:00',
                'ngay_cap_nhat' => '2026-03-01 05:27:00',
            ),
            28 => 
            array (
                'id' => 29,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_360406.pdf',
                'lop_hoc_phan_id' => 17,
                'nguoi_tao_id' => 23,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-09-19 00:40:00',
                'ngay_cap_nhat' => '2025-09-19 00:40:00',
            ),
            29 => 
            array (
                'id' => 30,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_406019.zip',
                'lop_hoc_phan_id' => 18,
                'nguoi_tao_id' => 26,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-10 04:57:00',
                'ngay_cap_nhat' => '2026-05-10 04:57:00',
            ),
            30 => 
            array (
                'id' => 31,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_671194.jpg',
                'lop_hoc_phan_id' => 19,
                'nguoi_tao_id' => 27,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-09-04 17:55:00',
                'ngay_cap_nhat' => '2025-09-04 17:55:00',
            ),
            31 => 
            array (
                'id' => 32,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_177353.jpg',
                'lop_hoc_phan_id' => 20,
                'nguoi_tao_id' => 29,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-12-30 23:58:00',
                'ngay_cap_nhat' => '2025-12-30 23:58:00',
            ),
            32 => 
            array (
                'id' => 33,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_626251.pptx',
                'lop_hoc_phan_id' => 21,
                'nguoi_tao_id' => 33,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-09-07 15:32:00',
                'ngay_cap_nhat' => '2025-09-07 15:32:00',
            ),
            33 => 
            array (
                'id' => 34,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_921110.pdf',
                'lop_hoc_phan_id' => 21,
                'nguoi_tao_id' => 33,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-10-26 17:54:00',
                'ngay_cap_nhat' => '2025-10-26 17:54:00',
            ),
            34 => 
            array (
                'id' => 35,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_968797.zip',
                'lop_hoc_phan_id' => 22,
                'nguoi_tao_id' => 30,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-13 20:24:00',
                'ngay_cap_nhat' => '2025-04-13 20:24:00',
            ),
            35 => 
            array (
                'id' => 36,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_755106.docx',
                'lop_hoc_phan_id' => 23,
                'nguoi_tao_id' => 37,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-04-12 16:19:00',
                'ngay_cap_nhat' => '2026-04-12 16:19:00',
            ),
            36 => 
            array (
                'id' => 37,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_673028.zip',
                'lop_hoc_phan_id' => 24,
                'nguoi_tao_id' => 38,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-09-24 01:38:00',
                'ngay_cap_nhat' => '2024-09-24 01:38:00',
            ),
            37 => 
            array (
                'id' => 38,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_778058.pdf',
                'lop_hoc_phan_id' => 25,
                'nguoi_tao_id' => 39,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-22 09:59:00',
                'ngay_cap_nhat' => '2026-05-22 09:59:00',
            ),
            38 => 
            array (
                'id' => 39,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_780433.pdf',
                'lop_hoc_phan_id' => 25,
                'nguoi_tao_id' => 39,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-01-21 11:04:00',
                'ngay_cap_nhat' => '2026-01-21 11:04:00',
            ),
            39 => 
            array (
                'id' => 40,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_172827.zip',
                'lop_hoc_phan_id' => 26,
                'nguoi_tao_id' => 41,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-08-01 18:15:00',
                'ngay_cap_nhat' => '2025-08-01 18:15:00',
            ),
            40 => 
            array (
                'id' => 41,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_677637.jpg',
                'lop_hoc_phan_id' => 27,
                'nguoi_tao_id' => 30,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-08-13 22:57:00',
                'ngay_cap_nhat' => '2025-08-13 22:57:00',
            ),
            41 => 
            array (
                'id' => 42,
                'tieu_de' => 'Slide bài giảng chương 2',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_791281.xlsx',
                'lop_hoc_phan_id' => 27,
                'nguoi_tao_id' => 30,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-27 20:01:00',
                'ngay_cap_nhat' => '2024-10-27 20:01:00',
            ),
            42 => 
            array (
                'id' => 43,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_960270.xlsx',
                'lop_hoc_phan_id' => 28,
                'nguoi_tao_id' => 30,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-25 06:21:00',
                'ngay_cap_nhat' => '2024-10-25 06:21:00',
            ),
            43 => 
            array (
                'id' => 44,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_973128.pdf',
                'lop_hoc_phan_id' => 29,
                'nguoi_tao_id' => 41,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-08-14 23:21:00',
                'ngay_cap_nhat' => '2025-08-14 23:21:00',
            ),
            44 => 
            array (
                'id' => 45,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_996332.jpg',
                'lop_hoc_phan_id' => 30,
                'nguoi_tao_id' => 40,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-04-15 18:57:00',
                'ngay_cap_nhat' => '2024-04-15 18:57:00',
            ),
            45 => 
            array (
                'id' => 46,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_122069.docx',
                'lop_hoc_phan_id' => 31,
                'nguoi_tao_id' => 49,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-02 19:47:00',
                'ngay_cap_nhat' => '2025-04-02 19:47:00',
            ),
            46 => 
            array (
                'id' => 47,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_378293.xlsx',
                'lop_hoc_phan_id' => 32,
                'nguoi_tao_id' => 44,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-04 23:02:00',
                'ngay_cap_nhat' => '2024-11-04 23:02:00',
            ),
            47 => 
            array (
                'id' => 48,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_673028.zip',
                'lop_hoc_phan_id' => 33,
                'nguoi_tao_id' => 43,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-07-04 07:41:00',
                'ngay_cap_nhat' => '2025-07-04 07:41:00',
            ),
            48 => 
            array (
                'id' => 49,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_374721.docx',
                'lop_hoc_phan_id' => 34,
                'nguoi_tao_id' => 47,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-12-07 07:01:00',
                'ngay_cap_nhat' => '2024-12-07 07:01:00',
            ),
            49 => 
            array (
                'id' => 50,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_628291.zip',
                'lop_hoc_phan_id' => 34,
                'nguoi_tao_id' => 47,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-04-03 06:34:00',
                'ngay_cap_nhat' => '2026-04-03 06:34:00',
            ),
            50 => 
            array (
                'id' => 51,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_509783.pptx',
                'lop_hoc_phan_id' => 35,
                'nguoi_tao_id' => 43,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-25 12:49:00',
                'ngay_cap_nhat' => '2024-03-25 12:49:00',
            ),
            51 => 
            array (
                'id' => 52,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_755106.docx',
                'lop_hoc_phan_id' => 35,
                'nguoi_tao_id' => 43,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-16 22:27:00',
                'ngay_cap_nhat' => '2025-04-16 22:27:00',
            ),
            52 => 
            array (
                'id' => 53,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_968797.zip',
                'lop_hoc_phan_id' => 36,
                'nguoi_tao_id' => 45,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-05-31 19:57:00',
                'ngay_cap_nhat' => '2024-05-31 19:57:00',
            ),
            53 => 
            array (
                'id' => 54,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_879677.docx',
                'lop_hoc_phan_id' => 37,
                'nguoi_tao_id' => 47,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-17 13:58:00',
                'ngay_cap_nhat' => '2025-01-17 13:58:00',
            ),
            54 => 
            array (
                'id' => 55,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_769399.zip',
                'lop_hoc_phan_id' => 37,
                'nguoi_tao_id' => 47,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-09-25 02:37:00',
                'ngay_cap_nhat' => '2024-09-25 02:37:00',
            ),
            55 => 
            array (
                'id' => 56,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_993077.pdf',
                'lop_hoc_phan_id' => 38,
                'nguoi_tao_id' => 48,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-07 17:36:00',
                'ngay_cap_nhat' => '2026-03-07 17:36:00',
            ),
            56 => 
            array (
                'id' => 57,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_888363.docx',
                'lop_hoc_phan_id' => 39,
                'nguoi_tao_id' => 48,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-13 01:04:00',
                'ngay_cap_nhat' => '2026-05-13 01:04:00',
            ),
            57 => 
            array (
                'id' => 58,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_968797.zip',
                'lop_hoc_phan_id' => 40,
                'nguoi_tao_id' => 45,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-08-03 09:02:00',
                'ngay_cap_nhat' => '2024-08-03 09:02:00',
            ),
            58 => 
            array (
                'id' => 59,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_108890.pdf',
                'lop_hoc_phan_id' => 41,
                'nguoi_tao_id' => 60,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-26 04:38:00',
                'ngay_cap_nhat' => '2024-11-26 04:38:00',
            ),
            59 => 
            array (
                'id' => 60,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_374721.docx',
                'lop_hoc_phan_id' => 41,
                'nguoi_tao_id' => 60,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-12-05 03:42:00',
                'ngay_cap_nhat' => '2025-12-05 03:42:00',
            ),
            60 => 
            array (
                'id' => 61,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_527070.pdf',
                'lop_hoc_phan_id' => 42,
                'nguoi_tao_id' => 52,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-08-10 06:31:00',
                'ngay_cap_nhat' => '2025-08-10 06:31:00',
            ),
            61 => 
            array (
                'id' => 62,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_863481.jpg',
                'lop_hoc_phan_id' => 43,
                'nguoi_tao_id' => 51,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-01-31 09:23:00',
                'ngay_cap_nhat' => '2026-01-31 09:23:00',
            ),
            62 => 
            array (
                'id' => 63,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_108890.pdf',
                'lop_hoc_phan_id' => 43,
                'nguoi_tao_id' => 51,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-07-24 08:20:00',
                'ngay_cap_nhat' => '2025-07-24 08:20:00',
            ),
            63 => 
            array (
                'id' => 64,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_970893.pptx',
                'lop_hoc_phan_id' => 44,
                'nguoi_tao_id' => 54,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-03-27 22:39:00',
                'ngay_cap_nhat' => '2025-03-27 22:39:00',
            ),
            64 => 
            array (
                'id' => 65,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_205102.jpg',
                'lop_hoc_phan_id' => 45,
                'nguoi_tao_id' => 50,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-08-27 04:53:00',
                'ngay_cap_nhat' => '2024-08-27 04:53:00',
            ),
            65 => 
            array (
                'id' => 66,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_877039.zip',
                'lop_hoc_phan_id' => 45,
                'nguoi_tao_id' => 50,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-01 17:13:00',
                'ngay_cap_nhat' => '2026-03-01 17:13:00',
            ),
            66 => 
            array (
                'id' => 67,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_438746.docx',
                'lop_hoc_phan_id' => 46,
                'nguoi_tao_id' => 61,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-08 07:44:00',
                'ngay_cap_nhat' => '2024-03-08 07:44:00',
            ),
            67 => 
            array (
                'id' => 68,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_615711.jpg',
                'lop_hoc_phan_id' => 47,
                'nguoi_tao_id' => 51,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-02-22 15:53:00',
                'ngay_cap_nhat' => '2024-02-22 15:53:00',
            ),
            68 => 
            array (
                'id' => 69,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_404969.docx',
                'lop_hoc_phan_id' => 47,
                'nguoi_tao_id' => 51,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-11 18:24:00',
                'ngay_cap_nhat' => '2024-11-11 18:24:00',
            ),
            69 => 
            array (
                'id' => 70,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_760393.docx',
                'lop_hoc_phan_id' => 48,
                'nguoi_tao_id' => 58,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-12 19:24:00',
                'ngay_cap_nhat' => '2024-11-12 19:24:00',
            ),
            70 => 
            array (
                'id' => 71,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_502810.xlsx',
                'lop_hoc_phan_id' => 48,
                'nguoi_tao_id' => 58,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-02-26 12:28:00',
                'ngay_cap_nhat' => '2025-02-26 12:28:00',
            ),
            71 => 
            array (
                'id' => 72,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_973128.pdf',
                'lop_hoc_phan_id' => 49,
                'nguoi_tao_id' => 61,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-02-23 05:42:00',
                'ngay_cap_nhat' => '2025-02-23 05:42:00',
            ),
            72 => 
            array (
                'id' => 73,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_877039.zip',
                'lop_hoc_phan_id' => 50,
                'nguoi_tao_id' => 59,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-04 17:48:00',
                'ngay_cap_nhat' => '2024-03-04 17:48:00',
            ),
            73 => 
            array (
                'id' => 74,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_628291.zip',
                'lop_hoc_phan_id' => 50,
                'nguoi_tao_id' => 59,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-10-16 10:59:00',
                'ngay_cap_nhat' => '2025-10-16 10:59:00',
            ),
            74 => 
            array (
                'id' => 75,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_842658.docx',
                'lop_hoc_phan_id' => 51,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-15 23:53:00',
                'ngay_cap_nhat' => '2025-01-15 23:53:00',
            ),
            75 => 
            array (
                'id' => 76,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_104359.xlsx',
                'lop_hoc_phan_id' => 51,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-04-12 23:59:00',
                'ngay_cap_nhat' => '2026-04-12 23:59:00',
            ),
            76 => 
            array (
                'id' => 77,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_780433.pdf',
                'lop_hoc_phan_id' => 52,
                'nguoi_tao_id' => 63,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-02-08 21:18:00',
                'ngay_cap_nhat' => '2026-02-08 21:18:00',
            ),
            77 => 
            array (
                'id' => 78,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_637559.xlsx',
                'lop_hoc_phan_id' => 53,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-24 05:24:00',
                'ngay_cap_nhat' => '2024-10-24 05:24:00',
            ),
            78 => 
            array (
                'id' => 79,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_769399.zip',
                'lop_hoc_phan_id' => 53,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-15 00:17:00',
                'ngay_cap_nhat' => '2024-06-15 00:17:00',
            ),
            79 => 
            array (
                'id' => 80,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_888363.docx',
                'lop_hoc_phan_id' => 54,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-31 17:18:00',
                'ngay_cap_nhat' => '2026-03-31 17:18:00',
            ),
            80 => 
            array (
                'id' => 81,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_285488.xlsx',
                'lop_hoc_phan_id' => 54,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-11 19:17:00',
                'ngay_cap_nhat' => '2024-03-11 19:17:00',
            ),
            81 => 
            array (
                'id' => 82,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_527070.pdf',
                'lop_hoc_phan_id' => 55,
                'nguoi_tao_id' => 68,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-04-12 20:51:00',
                'ngay_cap_nhat' => '2026-04-12 20:51:00',
            ),
            82 => 
            array (
                'id' => 83,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_549449.docx',
                'lop_hoc_phan_id' => 55,
                'nguoi_tao_id' => 68,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-12-11 18:42:00',
                'ngay_cap_nhat' => '2024-12-11 18:42:00',
            ),
            83 => 
            array (
                'id' => 84,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_883281.docx',
                'lop_hoc_phan_id' => 56,
                'nguoi_tao_id' => 69,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-30 14:01:00',
                'ngay_cap_nhat' => '2025-04-30 14:01:00',
            ),
            84 => 
            array (
                'id' => 85,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_147652.docx',
                'lop_hoc_phan_id' => 56,
                'nguoi_tao_id' => 69,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-05-23 01:22:00',
                'ngay_cap_nhat' => '2025-05-23 01:22:00',
            ),
            85 => 
            array (
                'id' => 86,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_671194.jpg',
                'lop_hoc_phan_id' => 57,
                'nguoi_tao_id' => 63,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-31 18:05:00',
                'ngay_cap_nhat' => '2024-03-31 18:05:00',
            ),
            86 => 
            array (
                'id' => 87,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_801655.xlsx',
                'lop_hoc_phan_id' => 57,
                'nguoi_tao_id' => 63,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-04-06 14:11:00',
                'ngay_cap_nhat' => '2024-04-06 14:11:00',
            ),
            87 => 
            array (
                'id' => 88,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_815520.docx',
                'lop_hoc_phan_id' => 58,
                'nguoi_tao_id' => 68,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-06-21 04:14:00',
                'ngay_cap_nhat' => '2025-06-21 04:14:00',
            ),
            88 => 
            array (
                'id' => 89,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_544420.pptx',
                'lop_hoc_phan_id' => 58,
                'nguoi_tao_id' => 68,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-10-25 20:03:00',
                'ngay_cap_nhat' => '2025-10-25 20:03:00',
            ),
            89 => 
            array (
                'id' => 90,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_963408.pdf',
                'lop_hoc_phan_id' => 59,
                'nguoi_tao_id' => 62,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-08-07 21:32:00',
                'ngay_cap_nhat' => '2024-08-07 21:32:00',
            ),
            90 => 
            array (
                'id' => 91,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_487040.jpg',
                'lop_hoc_phan_id' => 60,
                'nguoi_tao_id' => 66,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-08-20 22:14:00',
                'ngay_cap_nhat' => '2025-08-20 22:14:00',
            ),
            91 => 
            array (
                'id' => 92,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_815520.docx',
                'lop_hoc_phan_id' => 60,
                'nguoi_tao_id' => 66,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-21 00:43:00',
                'ngay_cap_nhat' => '2024-10-21 00:43:00',
            ),
            92 => 
            array (
                'id' => 93,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_769399.zip',
                'lop_hoc_phan_id' => 61,
                'nguoi_tao_id' => 76,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-24 03:04:00',
                'ngay_cap_nhat' => '2025-01-24 03:04:00',
            ),
            93 => 
            array (
                'id' => 94,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_254535.xlsx',
                'lop_hoc_phan_id' => 61,
                'nguoi_tao_id' => 76,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-07-08 02:15:00',
                'ngay_cap_nhat' => '2025-07-08 02:15:00',
            ),
            94 => 
            array (
                'id' => 95,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_972950.pdf',
                'lop_hoc_phan_id' => 62,
                'nguoi_tao_id' => 79,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-30 21:26:00',
                'ngay_cap_nhat' => '2026-05-30 21:26:00',
            ),
            95 => 
            array (
                'id' => 96,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_198685.pdf',
                'lop_hoc_phan_id' => 63,
                'nguoi_tao_id' => 74,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-26 00:20:00',
                'ngay_cap_nhat' => '2024-06-26 00:20:00',
            ),
            96 => 
            array (
                'id' => 97,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_671194.jpg',
                'lop_hoc_phan_id' => 64,
                'nguoi_tao_id' => 77,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-11-29 11:30:00',
                'ngay_cap_nhat' => '2025-11-29 11:30:00',
            ),
            97 => 
            array (
                'id' => 98,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_842658.docx',
                'lop_hoc_phan_id' => 64,
                'nguoi_tao_id' => 77,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-07-14 11:02:00',
                'ngay_cap_nhat' => '2024-07-14 11:02:00',
            ),
            98 => 
            array (
                'id' => 99,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_628291.zip',
                'lop_hoc_phan_id' => 65,
                'nguoi_tao_id' => 74,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-05-19 19:13:00',
                'ngay_cap_nhat' => '2024-05-19 19:13:00',
            ),
            99 => 
            array (
                'id' => 100,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_863094.docx',
                'lop_hoc_phan_id' => 65,
                'nguoi_tao_id' => 74,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-02-02 23:32:00',
                'ngay_cap_nhat' => '2026-02-02 23:32:00',
            ),
            100 => 
            array (
                'id' => 101,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_329242.pdf',
                'lop_hoc_phan_id' => 66,
                'nguoi_tao_id' => 78,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-31 18:02:00',
                'ngay_cap_nhat' => '2026-05-31 18:02:00',
            ),
            101 => 
            array (
                'id' => 102,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_495896.docx',
                'lop_hoc_phan_id' => 66,
                'nguoi_tao_id' => 78,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-03-22 20:05:00',
                'ngay_cap_nhat' => '2026-03-22 20:05:00',
            ),
            102 => 
            array (
                'id' => 103,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_735553.pdf',
                'lop_hoc_phan_id' => 67,
                'nguoi_tao_id' => 73,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-09-11 20:35:00',
                'ngay_cap_nhat' => '2025-09-11 20:35:00',
            ),
            103 => 
            array (
                'id' => 104,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_955524.jpg',
                'lop_hoc_phan_id' => 68,
                'nguoi_tao_id' => 73,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-04-28 01:38:00',
                'ngay_cap_nhat' => '2026-04-28 01:38:00',
            ),
            104 => 
            array (
                'id' => 105,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_857135.docx',
                'lop_hoc_phan_id' => 68,
                'nguoi_tao_id' => 73,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-07-17 14:20:00',
                'ngay_cap_nhat' => '2025-07-17 14:20:00',
            ),
            105 => 
            array (
                'id' => 106,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_696360.docx',
                'lop_hoc_phan_id' => 69,
                'nguoi_tao_id' => 74,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-07 10:15:00',
                'ngay_cap_nhat' => '2024-10-07 10:15:00',
            ),
            106 => 
            array (
                'id' => 107,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_168492.zip',
                'lop_hoc_phan_id' => 69,
                'nguoi_tao_id' => 74,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-05-12 10:47:00',
                'ngay_cap_nhat' => '2025-05-12 10:47:00',
            ),
            107 => 
            array (
                'id' => 108,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_863481.jpg',
                'lop_hoc_phan_id' => 70,
                'nguoi_tao_id' => 75,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-02-20 13:23:00',
                'ngay_cap_nhat' => '2026-02-20 13:23:00',
            ),
            108 => 
            array (
                'id' => 109,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_482615.docx',
                'lop_hoc_phan_id' => 71,
                'nguoi_tao_id' => 81,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-04-19 11:41:00',
                'ngay_cap_nhat' => '2024-04-19 11:41:00',
            ),
            109 => 
            array (
                'id' => 110,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_204415.xlsx',
                'lop_hoc_phan_id' => 72,
                'nguoi_tao_id' => 85,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-04-16 13:14:00',
                'ngay_cap_nhat' => '2026-04-16 13:14:00',
            ),
            110 => 
            array (
                'id' => 111,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_636196.docx',
                'lop_hoc_phan_id' => 72,
                'nguoi_tao_id' => 85,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-08 13:43:00',
                'ngay_cap_nhat' => '2024-10-08 13:43:00',
            ),
            111 => 
            array (
                'id' => 112,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_480977.pptx',
                'lop_hoc_phan_id' => 73,
                'nguoi_tao_id' => 82,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-15 10:07:00',
                'ngay_cap_nhat' => '2025-01-15 10:07:00',
            ),
            112 => 
            array (
                'id' => 113,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_960270.xlsx',
                'lop_hoc_phan_id' => 74,
                'nguoi_tao_id' => 85,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-07-02 04:36:00',
                'ngay_cap_nhat' => '2025-07-02 04:36:00',
            ),
            113 => 
            array (
                'id' => 114,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_829937.xlsx',
                'lop_hoc_phan_id' => 75,
                'nguoi_tao_id' => 83,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-05-10 00:10:00',
                'ngay_cap_nhat' => '2025-05-10 00:10:00',
            ),
            114 => 
            array (
                'id' => 115,
                'tieu_de' => 'Slide bài giảng chương 2',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_960270.xlsx',
                'lop_hoc_phan_id' => 75,
                'nguoi_tao_id' => 83,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-10-27 17:45:00',
                'ngay_cap_nhat' => '2024-10-27 17:45:00',
            ),
            115 => 
            array (
                'id' => 116,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_755106.docx',
                'lop_hoc_phan_id' => 76,
                'nguoi_tao_id' => 81,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-03-06 13:01:00',
                'ngay_cap_nhat' => '2024-03-06 13:01:00',
            ),
            116 => 
            array (
                'id' => 117,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_122069.docx',
                'lop_hoc_phan_id' => 76,
                'nguoi_tao_id' => 81,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-15 16:55:00',
                'ngay_cap_nhat' => '2024-06-15 16:55:00',
            ),
            117 => 
            array (
                'id' => 118,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_830532.jpg',
                'lop_hoc_phan_id' => 77,
                'nguoi_tao_id' => 86,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-10 12:44:00',
                'ngay_cap_nhat' => '2024-06-10 12:44:00',
            ),
            118 => 
            array (
                'id' => 119,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_696360.docx',
                'lop_hoc_phan_id' => 77,
                'nguoi_tao_id' => 86,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-01 10:57:00',
                'ngay_cap_nhat' => '2024-06-01 10:57:00',
            ),
            119 => 
            array (
                'id' => 120,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_528178.jpg',
                'lop_hoc_phan_id' => 78,
                'nguoi_tao_id' => 84,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-04-16 23:58:00',
                'ngay_cap_nhat' => '2024-04-16 23:58:00',
            ),
            120 => 
            array (
                'id' => 121,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_204415.xlsx',
                'lop_hoc_phan_id' => 78,
                'nguoi_tao_id' => 84,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-03-25 20:28:00',
                'ngay_cap_nhat' => '2025-03-25 20:28:00',
            ),
            121 => 
            array (
                'id' => 122,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_374721.docx',
                'lop_hoc_phan_id' => 79,
                'nguoi_tao_id' => 84,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-01-17 04:46:00',
                'ngay_cap_nhat' => '2026-01-17 04:46:00',
            ),
            122 => 
            array (
                'id' => 123,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_863094.docx',
                'lop_hoc_phan_id' => 79,
                'nguoi_tao_id' => 84,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-04-26 04:57:00',
                'ngay_cap_nhat' => '2024-04-26 04:57:00',
            ),
            123 => 
            array (
                'id' => 124,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_197784.pptx',
                'lop_hoc_phan_id' => 80,
                'nguoi_tao_id' => 82,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-02-23 10:28:00',
                'ngay_cap_nhat' => '2025-02-23 10:28:00',
            ),
            124 => 
            array (
                'id' => 125,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_312149.jpg',
                'lop_hoc_phan_id' => 81,
                'nguoi_tao_id' => 89,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-09-25 09:31:00',
                'ngay_cap_nhat' => '2024-09-25 09:31:00',
            ),
            125 => 
            array (
                'id' => 126,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_637559.xlsx',
                'lop_hoc_phan_id' => 82,
                'nguoi_tao_id' => 90,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-07-22 18:32:00',
                'ngay_cap_nhat' => '2025-07-22 18:32:00',
            ),
            126 => 
            array (
                'id' => 127,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_480977.pptx',
                'lop_hoc_phan_id' => 82,
                'nguoi_tao_id' => 90,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-12-27 12:20:00',
                'ngay_cap_nhat' => '2024-12-27 12:20:00',
            ),
            127 => 
            array (
                'id' => 128,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_487040.jpg',
                'lop_hoc_phan_id' => 83,
                'nguoi_tao_id' => 92,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-05-14 23:56:00',
                'ngay_cap_nhat' => '2026-05-14 23:56:00',
            ),
            128 => 
            array (
                'id' => 129,
                'tieu_de' => 'Hướng dẫn làm đồ án',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_637559.xlsx',
                'lop_hoc_phan_id' => 84,
                'nguoi_tao_id' => 88,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-11 18:56:00',
                'ngay_cap_nhat' => '2024-11-11 18:56:00',
            ),
            129 => 
            array (
                'id' => 130,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_970893.pptx',
                'lop_hoc_phan_id' => 85,
                'nguoi_tao_id' => 92,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-11-18 05:07:00',
                'ngay_cap_nhat' => '2024-11-18 05:07:00',
            ),
            130 => 
            array (
                'id' => 131,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_350725.jpg',
                'lop_hoc_phan_id' => 85,
                'nguoi_tao_id' => 92,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-06-13 14:14:00',
                'ngay_cap_nhat' => '2025-06-13 14:14:00',
            ),
            131 => 
            array (
                'id' => 132,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_815520.docx',
                'lop_hoc_phan_id' => 86,
                'nguoi_tao_id' => 92,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-10-13 03:59:00',
                'ngay_cap_nhat' => '2025-10-13 03:59:00',
            ),
            132 => 
            array (
                'id' => 133,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_438746.docx',
                'lop_hoc_phan_id' => 87,
                'nguoi_tao_id' => 94,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-05-09 06:35:00',
                'ngay_cap_nhat' => '2024-05-09 06:35:00',
            ),
            133 => 
            array (
                'id' => 134,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_487040.jpg',
                'lop_hoc_phan_id' => 88,
                'nguoi_tao_id' => 89,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-08-06 17:51:00',
                'ngay_cap_nhat' => '2025-08-06 17:51:00',
            ),
            134 => 
            array (
                'id' => 135,
                'tieu_de' => 'Giáo trình môn học',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_288540.xlsx',
                'lop_hoc_phan_id' => 89,
                'nguoi_tao_id' => 92,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-06-02 00:23:00',
                'ngay_cap_nhat' => '2026-06-02 00:23:00',
            ),
            135 => 
            array (
                'id' => 136,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_104359.xlsx',
                'lop_hoc_phan_id' => 90,
                'nguoi_tao_id' => 93,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2026-02-19 14:33:00',
                'ngay_cap_nhat' => '2026-02-19 14:33:00',
            ),
            136 => 
            array (
                'id' => 137,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_696360.docx',
                'lop_hoc_phan_id' => 91,
                'nguoi_tao_id' => 97,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-05-23 22:45:00',
                'ngay_cap_nhat' => '2024-05-23 22:45:00',
            ),
            137 => 
            array (
                'id' => 138,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_981610.docx',
                'lop_hoc_phan_id' => 92,
                'nguoi_tao_id' => 101,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-06-20 08:05:00',
                'ngay_cap_nhat' => '2025-06-20 08:05:00',
            ),
            138 => 
            array (
                'id' => 139,
                'tieu_de' => 'Bộ câu hỏi trắc nghiệm ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_615711.jpg',
                'lop_hoc_phan_id' => 93,
                'nguoi_tao_id' => 102,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-01-28 02:47:00',
                'ngay_cap_nhat' => '2025-01-28 02:47:00',
            ),
            139 => 
            array (
                'id' => 140,
                'tieu_de' => 'Slide bài giảng chương 1',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_219879.jpg',
                'lop_hoc_phan_id' => 94,
                'nguoi_tao_id' => 97,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-07-10 16:21:00',
                'ngay_cap_nhat' => '2024-07-10 16:21:00',
            ),
            140 => 
            array (
                'id' => 141,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_465484.docx',
                'lop_hoc_phan_id' => 95,
                'nguoi_tao_id' => 96,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-12-20 02:45:00',
                'ngay_cap_nhat' => '2025-12-20 02:45:00',
            ),
            141 => 
            array (
                'id' => 142,
                'tieu_de' => 'Tài liệu tham khảo mở rộng',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_963408.pdf',
                'lop_hoc_phan_id' => 95,
                'nguoi_tao_id' => 96,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-19 03:59:00',
                'ngay_cap_nhat' => '2025-04-19 03:59:00',
            ),
            142 => 
            array (
                'id' => 143,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_963408.pdf',
                'lop_hoc_phan_id' => 96,
                'nguoi_tao_id' => 101,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-11-11 20:00:00',
                'ngay_cap_nhat' => '2025-11-11 20:00:00',
            ),
            143 => 
            array (
                'id' => 144,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_954222.jpg',
                'lop_hoc_phan_id' => 96,
                'nguoi_tao_id' => 101,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-09-23 12:55:00',
                'ngay_cap_nhat' => '2025-09-23 12:55:00',
            ),
            144 => 
            array (
                'id' => 145,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_946699.docx',
                'lop_hoc_phan_id' => 97,
                'nguoi_tao_id' => 96,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-05-27 04:31:00',
                'ngay_cap_nhat' => '2025-05-27 04:31:00',
            ),
            145 => 
            array (
                'id' => 146,
                'tieu_de' => 'Biểu mẫu báo cáo thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_198685.pdf',
                'lop_hoc_phan_id' => 98,
                'nguoi_tao_id' => 101,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2024-06-14 06:40:00',
                'ngay_cap_nhat' => '2024-06-14 06:40:00',
            ),
            146 => 
            array (
                'id' => 147,
                'tieu_de' => 'Đề cương ôn tập',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_760460.pptx',
                'lop_hoc_phan_id' => 99,
                'nguoi_tao_id' => 101,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-20 02:31:00',
                'ngay_cap_nhat' => '2025-04-20 02:31:00',
            ),
            147 => 
            array (
                'id' => 148,
                'tieu_de' => 'Tài liệu thực hành',
                'mo_ta' => 'Tài liệu phục vụ học tập, sinh viên vui lòng tải về và nghiên cứu trước khi lên lớp.',
                'duong_dan_file' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_963408.pdf',
                'lop_hoc_phan_id' => 100,
                'nguoi_tao_id' => 98,
                'trang_thai' => 'hien_thi',
                'ngay_tao' => '2025-04-04 22:16:00',
                'ngay_cap_nhat' => '2025-04-04 22:16:00',
            ),
        ));
        
        
    }
}