<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TepTinTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tep_tin')->delete();
        
        \DB::table('tep_tin')->insert(array (
            0 => 
            array (
                'id' => 1,
                'ten_file' => 'DapAnThamKhao_001.pptx',
                'ten_file_luu' => 'dapanthamkhao_760460.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_760460.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 3600.76,
                'nguoi_tao_id' => 236,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-22 02:30:00',
            ),
            1 => 
            array (
                'id' => 2,
                'ten_file' => 'GiaoTrinh_002.xlsx',
                'ten_file_luu' => 'giaotrinh_628345.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_628345.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 3964.88,
                'nguoi_tao_id' => 45,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-10-06 08:44:00',
            ),
            2 => 
            array (
                'id' => 3,
                'ten_file' => 'HuongDanThucHanh_003.docx',
                'ten_file_luu' => 'huongdanthuchanh_147652.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_147652.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 4781.22,
                'nguoi_tao_id' => 18,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-04-24 22:12:00',
            ),
            3 => 
            array (
                'id' => 4,
                'ten_file' => 'BieuMauNopBai_004.jpg',
                'ten_file_luu' => 'bieumaunopbai_619072.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_619072.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 3439.24,
                'nguoi_tao_id' => 225,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-07-10 02:10:00',
            ),
            4 => 
            array (
                'id' => 5,
                'ten_file' => 'GiaoTrinh_005.xlsx',
                'ten_file_luu' => 'giaotrinh_502810.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_502810.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 2834.37,
                'nguoi_tao_id' => 102,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-17 19:17:00',
            ),
            5 => 
            array (
                'id' => 6,
                'ten_file' => 'DeCuongMonHoc_006.docx',
                'ten_file_luu' => 'decuongmonhoc_103775.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_103775.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 842.02,
                'nguoi_tao_id' => 58,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-09-29 22:00:00',
            ),
            6 => 
            array (
                'id' => 7,
                'ten_file' => 'DapAnThamKhao_007.zip',
                'ten_file_luu' => 'dapanthamkhao_628291.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_628291.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 3553.38,
                'nguoi_tao_id' => 137,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-23 09:54:00',
            ),
            7 => 
            array (
                'id' => 8,
                'ten_file' => 'HuongDanThucHanh_008.docx',
                'ten_file_luu' => 'huongdanthuchanh_842658.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_842658.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1379.15,
                'nguoi_tao_id' => 33,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-25 07:02:00',
            ),
            8 => 
            array (
                'id' => 9,
                'ten_file' => 'SlideBaiHoc_009.zip',
                'ten_file_luu' => 'slidebaihoc_406019.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_406019.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 243.5,
                'nguoi_tao_id' => 40,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-11 04:17:00',
            ),
            9 => 
            array (
                'id' => 10,
                'ten_file' => 'SlideBaiHoc_010.pdf',
                'ten_file_luu' => 'slidebaihoc_963408.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_963408.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 1089.36,
                'nguoi_tao_id' => 32,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-02 20:22:00',
            ),
            10 => 
            array (
                'id' => 11,
                'ten_file' => 'KeHoachHoc_011.jpg',
                'ten_file_luu' => 'kehoachhoc_487040.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_487040.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 1656.58,
                'nguoi_tao_id' => 245,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-01-23 17:16:00',
            ),
            11 => 
            array (
                'id' => 12,
                'ten_file' => 'DeCuongMonHoc_012.jpg',
                'ten_file_luu' => 'decuongmonhoc_528178.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_528178.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 4496.76,
                'nguoi_tao_id' => 78,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-12-29 01:40:00',
            ),
            12 => 
            array (
                'id' => 13,
                'ten_file' => 'BaoCaoDoAn_013.pdf',
                'ten_file_luu' => 'baocaodoan_329931.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_329931.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 3665.86,
                'nguoi_tao_id' => 74,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-30 08:01:00',
            ),
            13 => 
            array (
                'id' => 14,
                'ten_file' => 'KeHoachHoc_014.zip',
                'ten_file_luu' => 'kehoachhoc_211613.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_211613.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 3626.88,
                'nguoi_tao_id' => 179,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-02-26 20:16:00',
            ),
            14 => 
            array (
                'id' => 15,
                'ten_file' => 'KeHoachHoc_015.jpg',
                'ten_file_luu' => 'kehoachhoc_677637.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_677637.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 1070.49,
                'nguoi_tao_id' => 116,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-09-13 10:17:00',
            ),
            15 => 
            array (
                'id' => 16,
                'ten_file' => 'KeHoachHoc_016.docx',
                'ten_file_luu' => 'kehoachhoc_760393.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_760393.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 4048.28,
                'nguoi_tao_id' => 195,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-11 04:28:00',
            ),
            16 => 
            array (
                'id' => 17,
                'ten_file' => 'BieuMauNopBai_017.docx',
                'ten_file_luu' => 'bieumaunopbai_486547.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_486547.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 784.25,
                'nguoi_tao_id' => 125,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-06 15:11:00',
            ),
            17 => 
            array (
                'id' => 18,
                'ten_file' => 'DeCuongMonHoc_018.xlsx',
                'ten_file_luu' => 'decuongmonhoc_955216.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_955216.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4318.64,
                'nguoi_tao_id' => 51,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-09-06 15:46:00',
            ),
            18 => 
            array (
                'id' => 19,
                'ten_file' => 'HuongDanThucHanh_019.docx',
                'ten_file_luu' => 'huongdanthuchanh_122069.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_122069.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1585.29,
                'nguoi_tao_id' => 229,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-31 12:43:00',
            ),
            19 => 
            array (
                'id' => 20,
                'ten_file' => 'SlideBaiHoc_020.zip',
                'ten_file_luu' => 'slidebaihoc_172827.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_172827.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 760.44,
                'nguoi_tao_id' => 112,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-09 14:58:00',
            ),
            20 => 
            array (
                'id' => 21,
                'ten_file' => 'BieuMauNopBai_021.jpg',
                'ten_file_luu' => 'bieumaunopbai_205102.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_205102.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 3635.32,
                'nguoi_tao_id' => 38,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-02-14 00:38:00',
            ),
            21 => 
            array (
                'id' => 22,
                'ten_file' => 'BieuMauNopBai_022.pdf',
                'ten_file_luu' => 'bieumaunopbai_502643.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_502643.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 152.54,
                'nguoi_tao_id' => 214,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-14 20:59:00',
            ),
            22 => 
            array (
                'id' => 23,
                'ten_file' => 'DeCuongMonHoc_023.pdf',
                'ten_file_luu' => 'decuongmonhoc_360406.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_360406.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 3862.08,
                'nguoi_tao_id' => 71,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-06-26 20:38:00',
            ),
            23 => 
            array (
                'id' => 24,
                'ten_file' => 'BaiGiang_024.pdf',
                'ten_file_luu' => 'baigiang_930116.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_930116.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 576.38,
                'nguoi_tao_id' => 191,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-05-18 10:54:00',
            ),
            24 => 
            array (
                'id' => 25,
                'ten_file' => 'TaiLieuThamKhao_025.jpg',
                'ten_file_luu' => 'tailieuthamkhao_312149.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_312149.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 739.19,
                'nguoi_tao_id' => 197,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-08-30 14:52:00',
            ),
            25 => 
            array (
                'id' => 26,
                'ten_file' => 'HuongDanThucHanh_026.docx',
                'ten_file_luu' => 'huongdanthuchanh_447871.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_447871.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 2420.6,
                'nguoi_tao_id' => 65,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-03-29 17:44:00',
            ),
            26 => 
            array (
                'id' => 27,
                'ten_file' => 'GiaoTrinh_027.pptx',
                'ten_file_luu' => 'giaotrinh_229054.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_229054.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 154.98,
                'nguoi_tao_id' => 14,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-16 17:18:00',
            ),
            27 => 
            array (
                'id' => 28,
                'ten_file' => 'GiaoTrinh_028.pdf',
                'ten_file_luu' => 'giaotrinh_977116.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_977116.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2105.66,
                'nguoi_tao_id' => 3,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-09-17 00:14:00',
            ),
            28 => 
            array (
                'id' => 29,
                'ten_file' => 'BieuMauNopBai_029.xlsx',
                'ten_file_luu' => 'bieumaunopbai_254535.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_254535.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 1798.88,
                'nguoi_tao_id' => 76,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-09-19 21:24:00',
            ),
            29 => 
            array (
                'id' => 30,
                'ten_file' => 'TaiLieuThamKhao_030.jpg',
                'ten_file_luu' => 'tailieuthamkhao_615711.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_615711.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 889.32,
                'nguoi_tao_id' => 31,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-09-17 03:18:00',
            ),
            30 => 
            array (
                'id' => 31,
                'ten_file' => 'TaiLieuThamKhao_031.pptx',
                'ten_file_luu' => 'tailieuthamkhao_745604.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_745604.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1701.94,
                'nguoi_tao_id' => 95,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-04-27 01:38:00',
            ),
            31 => 
            array (
                'id' => 32,
                'ten_file' => 'DeCuongMonHoc_032.docx',
                'ten_file_luu' => 'decuongmonhoc_549449.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_549449.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 2675.88,
                'nguoi_tao_id' => 156,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-08-04 21:27:00',
            ),
            32 => 
            array (
                'id' => 33,
                'ten_file' => 'HuongDanThucHanh_033.docx',
                'ten_file_luu' => 'huongdanthuchanh_755106.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_755106.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 4096.93,
                'nguoi_tao_id' => 92,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-17 08:58:00',
            ),
            33 => 
            array (
                'id' => 34,
                'ten_file' => 'BaoCaoDoAn_034.xlsx',
                'ten_file_luu' => 'baocaodoan_378293.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_378293.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4063.06,
                'nguoi_tao_id' => 185,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-04-28 02:50:00',
            ),
            34 => 
            array (
                'id' => 35,
                'ten_file' => 'DeCuongMonHoc_035.pdf',
                'ten_file_luu' => 'decuongmonhoc_915565.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_915565.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 3296.48,
                'nguoi_tao_id' => 84,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-01 12:28:00',
            ),
            35 => 
            array (
                'id' => 36,
                'ten_file' => 'DapAnThamKhao_036.jpg',
                'ten_file_luu' => 'dapanthamkhao_954222.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_954222.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 383.2,
                'nguoi_tao_id' => 150,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-13 23:17:00',
            ),
            36 => 
            array (
                'id' => 37,
                'ten_file' => 'TaiLieuThamKhao_037.docx',
                'ten_file_luu' => 'tailieuthamkhao_438746.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_438746.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 4974.12,
                'nguoi_tao_id' => 49,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-27 12:22:00',
            ),
            37 => 
            array (
                'id' => 38,
                'ten_file' => 'DapAnThamKhao_038.pptx',
                'ten_file_luu' => 'dapanthamkhao_544420.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_544420.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 2432.38,
                'nguoi_tao_id' => 252,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-30 19:50:00',
            ),
            38 => 
            array (
                'id' => 39,
                'ten_file' => 'BaoCaoDoAn_039.jpg',
                'ten_file_luu' => 'baocaodoan_244935.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_244935.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 4020.6,
                'nguoi_tao_id' => 170,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-09 12:26:00',
            ),
            39 => 
            array (
                'id' => 40,
                'ten_file' => 'DapAnThamKhao_040.zip',
                'ten_file_luu' => 'dapanthamkhao_664917.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_664917.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 2692.16,
                'nguoi_tao_id' => 139,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-08-03 07:24:00',
            ),
            40 => 
            array (
                'id' => 41,
                'ten_file' => 'KeHoachHoc_041.pdf',
                'ten_file_luu' => 'kehoachhoc_849649.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_849649.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2138.11,
                'nguoi_tao_id' => 150,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-04-06 22:51:00',
            ),
            41 => 
            array (
                'id' => 42,
                'ten_file' => 'SlideBaiHoc_042.jpg',
                'ten_file_luu' => 'slidebaihoc_837246.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_837246.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 481.89,
                'nguoi_tao_id' => 95,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-03 06:54:00',
            ),
            42 => 
            array (
                'id' => 43,
                'ten_file' => 'BaoCaoDoAn_043.pdf',
                'ten_file_luu' => 'baocaodoan_685498.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_685498.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2395.94,
                'nguoi_tao_id' => 37,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-23 01:58:00',
            ),
            43 => 
            array (
                'id' => 44,
                'ten_file' => 'BaoCaoDoAn_044.pptx',
                'ten_file_luu' => 'baocaodoan_989980.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_989980.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 4254.18,
                'nguoi_tao_id' => 202,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-05-19 04:18:00',
            ),
            44 => 
            array (
                'id' => 45,
                'ten_file' => 'DeCuongMonHoc_045.xlsx',
                'ten_file_luu' => 'decuongmonhoc_975825.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_975825.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4273.9,
                'nguoi_tao_id' => 251,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-07 07:13:00',
            ),
            45 => 
            array (
                'id' => 46,
                'ten_file' => 'BaiGiang_046.docx',
                'ten_file_luu' => 'baigiang_883281.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_883281.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 732.12,
                'nguoi_tao_id' => 249,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-01-13 22:09:00',
            ),
            46 => 
            array (
                'id' => 47,
                'ten_file' => 'BaiGiang_047.xlsx',
                'ten_file_luu' => 'baigiang_829937.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_829937.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4826.32,
                'nguoi_tao_id' => 98,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-03-27 22:06:00',
            ),
            47 => 
            array (
                'id' => 48,
                'ten_file' => 'KeHoachHoc_048.jpg',
                'ten_file_luu' => 'kehoachhoc_177353.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_177353.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 2410.29,
                'nguoi_tao_id' => 155,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-11 00:09:00',
            ),
            48 => 
            array (
                'id' => 49,
                'ten_file' => 'DeCuongMonHoc_049.pptx',
                'ten_file_luu' => 'decuongmonhoc_182830.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_182830.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1262.98,
                'nguoi_tao_id' => 6,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-09-05 13:09:00',
            ),
            49 => 
            array (
                'id' => 50,
                'ten_file' => 'DapAnThamKhao_050.docx',
                'ten_file_luu' => 'dapanthamkhao_879677.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_879677.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 743.56,
                'nguoi_tao_id' => 138,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-01-16 09:30:00',
            ),
            50 => 
            array (
                'id' => 51,
                'ten_file' => 'BaoCaoDoAn_051.xlsx',
                'ten_file_luu' => 'baocaodoan_565540.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_565540.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 3917.91,
                'nguoi_tao_id' => 180,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-14 09:07:00',
            ),
            51 => 
            array (
                'id' => 52,
                'ten_file' => 'BaiGiang_052.docx',
                'ten_file_luu' => 'baigiang_773662.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_773662.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 208.99,
                'nguoi_tao_id' => 195,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-27 16:10:00',
            ),
            52 => 
            array (
                'id' => 53,
                'ten_file' => 'BieuMauNopBai_053.pdf',
                'ten_file_luu' => 'bieumaunopbai_973128.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_973128.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2146.92,
                'nguoi_tao_id' => 245,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-05-11 17:45:00',
            ),
            53 => 
            array (
                'id' => 54,
                'ten_file' => 'KeHoachHoc_054.pptx',
                'ten_file_luu' => 'kehoachhoc_626251.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_626251.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1564.87,
                'nguoi_tao_id' => 61,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-09 05:17:00',
            ),
            54 => 
            array (
                'id' => 55,
                'ten_file' => 'GiaoTrinh_055.pdf',
                'ten_file_luu' => 'giaotrinh_495900.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_495900.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 4890.74,
                'nguoi_tao_id' => 35,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-02 06:25:00',
            ),
            55 => 
            array (
                'id' => 56,
                'ten_file' => 'BaiGiang_056.zip',
                'ten_file_luu' => 'baigiang_329540.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_329540.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 1991.84,
                'nguoi_tao_id' => 213,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-05 17:38:00',
            ),
            56 => 
            array (
                'id' => 57,
                'ten_file' => 'DapAnThamKhao_057.pdf',
                'ten_file_luu' => 'dapanthamkhao_600607.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_600607.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 1600.29,
                'nguoi_tao_id' => 167,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-21 12:10:00',
            ),
            57 => 
            array (
                'id' => 58,
                'ten_file' => 'BaoCaoDoAn_058.pdf',
                'ten_file_luu' => 'baocaodoan_778058.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_778058.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2149.9,
                'nguoi_tao_id' => 72,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-22 03:04:00',
            ),
            58 => 
            array (
                'id' => 59,
                'ten_file' => 'KeHoachHoc_059.pptx',
                'ten_file_luu' => 'kehoachhoc_916628.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_916628.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 4240.72,
                'nguoi_tao_id' => 10,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-03 09:10:00',
            ),
            59 => 
            array (
                'id' => 60,
                'ten_file' => 'TaiLieuThamKhao_060.zip',
                'ten_file_luu' => 'tailieuthamkhao_168492.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_168492.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 1098.95,
                'nguoi_tao_id' => 5,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-16 09:12:00',
            ),
            60 => 
            array (
                'id' => 61,
                'ten_file' => 'SlideBaiHoc_061.zip',
                'ten_file_luu' => 'slidebaihoc_769399.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_769399.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 4649.55,
                'nguoi_tao_id' => 64,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-02 02:36:00',
            ),
            61 => 
            array (
                'id' => 62,
                'ten_file' => 'BaiGiang_062.zip',
                'ten_file_luu' => 'baigiang_691123.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_691123.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 4933.15,
                'nguoi_tao_id' => 126,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-03-18 01:20:00',
            ),
            62 => 
            array (
                'id' => 63,
                'ten_file' => 'HuongDanThucHanh_063.pdf',
                'ten_file_luu' => 'huongdanthuchanh_108890.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_108890.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 4903.68,
                'nguoi_tao_id' => 195,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-16 12:32:00',
            ),
            63 => 
            array (
                'id' => 64,
                'ten_file' => 'BaoCaoDoAn_064.docx',
                'ten_file_luu' => 'baocaodoan_888363.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_888363.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1983.67,
                'nguoi_tao_id' => 94,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-06-12 22:43:00',
            ),
            64 => 
            array (
                'id' => 65,
                'ten_file' => 'BaoCaoDoAn_065.pdf',
                'ten_file_luu' => 'baocaodoan_527070.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_527070.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 4487.73,
                'nguoi_tao_id' => 131,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-14 16:51:00',
            ),
            65 => 
            array (
                'id' => 66,
                'ten_file' => 'BaiGiang_066.docx',
                'ten_file_luu' => 'baigiang_715698.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_715698.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 3990.54,
                'nguoi_tao_id' => 125,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-09-23 01:18:00',
            ),
            66 => 
            array (
                'id' => 67,
                'ten_file' => 'DeCuongMonHoc_067.docx',
                'ten_file_luu' => 'decuongmonhoc_815520.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_815520.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 2342.38,
                'nguoi_tao_id' => 229,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-11-02 02:45:00',
            ),
            67 => 
            array (
                'id' => 68,
                'ten_file' => 'SlideBaiHoc_068.docx',
                'ten_file_luu' => 'slidebaihoc_946699.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_946699.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 3423.23,
                'nguoi_tao_id' => 39,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-29 22:10:00',
            ),
            68 => 
            array (
                'id' => 69,
                'ten_file' => 'GiaoTrinh_069.zip',
                'ten_file_luu' => 'giaotrinh_864118.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_864118.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 3063.26,
                'nguoi_tao_id' => 136,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-29 10:28:00',
            ),
            69 => 
            array (
                'id' => 70,
                'ten_file' => 'BaoCaoDoAn_070.docx',
                'ten_file_luu' => 'baocaodoan_404969.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_404969.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1833.57,
                'nguoi_tao_id' => 222,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-17 01:57:00',
            ),
            70 => 
            array (
                'id' => 71,
                'ten_file' => 'BieuMauNopBai_071.jpg',
                'ten_file_luu' => 'bieumaunopbai_350725.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_350725.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 1083.66,
                'nguoi_tao_id' => 159,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-10-14 02:09:00',
            ),
            71 => 
            array (
                'id' => 72,
                'ten_file' => 'DapAnThamKhao_072.zip',
                'ten_file_luu' => 'dapanthamkhao_202137.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_202137.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 4033.4,
                'nguoi_tao_id' => 39,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-26 09:35:00',
            ),
            72 => 
            array (
                'id' => 73,
                'ten_file' => 'DapAnThamKhao_073.pdf',
                'ten_file_luu' => 'dapanthamkhao_198685.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_198685.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2301.3,
                'nguoi_tao_id' => 46,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-29 05:04:00',
            ),
            73 => 
            array (
                'id' => 74,
                'ten_file' => 'KeHoachHoc_074.pptx',
                'ten_file_luu' => 'kehoachhoc_480977.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_480977.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1799.17,
                'nguoi_tao_id' => 21,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-08-02 22:49:00',
            ),
            74 => 
            array (
                'id' => 75,
                'ten_file' => 'HuongDanThucHanh_075.xlsx',
                'ten_file_luu' => 'huongdanthuchanh_596250.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_596250.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4893.49,
                'nguoi_tao_id' => 198,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-28 20:59:00',
            ),
            75 => 
            array (
                'id' => 76,
                'ten_file' => 'TaiLieuThamKhao_076.docx',
                'ten_file_luu' => 'tailieuthamkhao_696360.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_696360.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 2466.88,
                'nguoi_tao_id' => 96,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-29 09:25:00',
            ),
            76 => 
            array (
                'id' => 77,
                'ten_file' => 'KeHoachHoc_077.xlsx',
                'ten_file_luu' => 'kehoachhoc_813644.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_813644.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 688.47,
                'nguoi_tao_id' => 96,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-07-09 19:20:00',
            ),
            77 => 
            array (
                'id' => 78,
                'ten_file' => 'TaiLieuThamKhao_078.pptx',
                'ten_file_luu' => 'tailieuthamkhao_815339.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_815339.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 2095.31,
                'nguoi_tao_id' => 118,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-27 21:02:00',
            ),
            78 => 
            array (
                'id' => 79,
                'ten_file' => 'BaiGiang_079.zip',
                'ten_file_luu' => 'baigiang_877039.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_877039.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 3963.42,
                'nguoi_tao_id' => 182,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-05-21 17:00:00',
            ),
            79 => 
            array (
                'id' => 80,
                'ten_file' => 'TaiLieuThamKhao_080.docx',
                'ten_file_luu' => 'tailieuthamkhao_404779.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_404779.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1910.32,
                'nguoi_tao_id' => 148,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-15 02:14:00',
            ),
            80 => 
            array (
                'id' => 81,
                'ten_file' => 'DapAnThamKhao_081.xlsx',
                'ten_file_luu' => 'dapanthamkhao_801655.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_801655.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 512.84,
                'nguoi_tao_id' => 122,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-05-25 20:34:00',
            ),
            81 => 
            array (
                'id' => 82,
                'ten_file' => 'TaiLieuThamKhao_082.xlsx',
                'ten_file_luu' => 'tailieuthamkhao_189991.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_189991.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 942.35,
                'nguoi_tao_id' => 30,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-13 13:12:00',
            ),
            82 => 
            array (
                'id' => 83,
                'ten_file' => 'BaoCaoDoAn_083.xlsx',
                'ten_file_luu' => 'baocaodoan_167603.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_167603.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 1620.56,
                'nguoi_tao_id' => 157,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-06-12 06:44:00',
            ),
            83 => 
            array (
                'id' => 84,
                'ten_file' => 'DapAnThamKhao_084.jpg',
                'ten_file_luu' => 'dapanthamkhao_219879.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_219879.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 1427.96,
                'nguoi_tao_id' => 12,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-08-12 04:30:00',
            ),
            84 => 
            array (
                'id' => 85,
                'ten_file' => 'SlideBaiHoc_085.docx',
                'ten_file_luu' => 'slidebaihoc_435740.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_435740.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 2862.62,
                'nguoi_tao_id' => 156,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-04-03 12:03:00',
            ),
            85 => 
            array (
                'id' => 86,
                'ten_file' => 'BieuMauNopBai_086.pptx',
                'ten_file_luu' => 'bieumaunopbai_596405.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_596405.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1106.43,
                'nguoi_tao_id' => 57,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-24 21:27:00',
            ),
            86 => 
            array (
                'id' => 87,
                'ten_file' => 'HuongDanThucHanh_087.pptx',
                'ten_file_luu' => 'huongdanthuchanh_766566.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_766566.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 921.72,
                'nguoi_tao_id' => 39,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-04-11 08:25:00',
            ),
            87 => 
            array (
                'id' => 88,
                'ten_file' => 'HuongDanThucHanh_088.pdf',
                'ten_file_luu' => 'huongdanthuchanh_846802.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_846802.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2284.53,
                'nguoi_tao_id' => 110,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-07-22 06:42:00',
            ),
            88 => 
            array (
                'id' => 89,
                'ten_file' => 'DeCuongMonHoc_089.pptx',
                'ten_file_luu' => 'decuongmonhoc_970893.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_970893.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 316.02,
                'nguoi_tao_id' => 232,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-14 10:48:00',
            ),
            89 => 
            array (
                'id' => 90,
                'ten_file' => 'DeCuongMonHoc_090.pptx',
                'ten_file_luu' => 'decuongmonhoc_308252.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_308252.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1778.92,
                'nguoi_tao_id' => 110,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-06-08 15:34:00',
            ),
            90 => 
            array (
                'id' => 91,
                'ten_file' => 'DeCuongMonHoc_091.jpg',
                'ten_file_luu' => 'decuongmonhoc_830532.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_830532.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 2212.08,
                'nguoi_tao_id' => 236,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-01-10 18:24:00',
            ),
            91 => 
            array (
                'id' => 92,
                'ten_file' => 'GiaoTrinh_092.pdf',
                'ten_file_luu' => 'giaotrinh_921110.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_921110.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 4474.21,
                'nguoi_tao_id' => 53,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-04-20 23:42:00',
            ),
            92 => 
            array (
                'id' => 93,
                'ten_file' => 'KeHoachHoc_093.zip',
                'ten_file_luu' => 'kehoachhoc_251642.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_251642.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 1652.48,
                'nguoi_tao_id' => 213,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-02-21 23:52:00',
            ),
            93 => 
            array (
                'id' => 94,
                'ten_file' => 'BaoCaoDoAn_094.jpg',
                'ten_file_luu' => 'baocaodoan_114875.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_114875.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 795.01,
                'nguoi_tao_id' => 120,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-07-01 15:55:00',
            ),
            94 => 
            array (
                'id' => 95,
                'ten_file' => 'TaiLieuThamKhao_095.pptx',
                'ten_file_luu' => 'tailieuthamkhao_930489.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_930489.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 4851.38,
                'nguoi_tao_id' => 107,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-27 16:46:00',
            ),
            95 => 
            array (
                'id' => 96,
                'ten_file' => 'DapAnThamKhao_096.pdf',
                'ten_file_luu' => 'dapanthamkhao_972950.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_972950.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 4293.47,
                'nguoi_tao_id' => 165,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-05-06 20:37:00',
            ),
            96 => 
            array (
                'id' => 97,
                'ten_file' => 'BaiGiang_097.pdf',
                'ten_file_luu' => 'baigiang_329242.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_329242.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 3741.25,
                'nguoi_tao_id' => 51,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-04-06 22:34:00',
            ),
            97 => 
            array (
                'id' => 98,
                'ten_file' => 'KeHoachHoc_098.docx',
                'ten_file_luu' => 'kehoachhoc_495896.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_495896.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1119.88,
                'nguoi_tao_id' => 56,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-08-14 21:36:00',
            ),
            98 => 
            array (
                'id' => 99,
                'ten_file' => 'BaoCaoDoAn_099.pdf',
                'ten_file_luu' => 'baocaodoan_953309.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_953309.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 1850.78,
                'nguoi_tao_id' => 80,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-12-11 16:52:00',
            ),
            99 => 
            array (
                'id' => 100,
                'ten_file' => 'DapAnThamKhao_100.pdf',
                'ten_file_luu' => 'dapanthamkhao_780433.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/dapanthamkhao_780433.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 4995.29,
                'nguoi_tao_id' => 108,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-27 11:22:00',
            ),
            100 => 
            array (
                'id' => 101,
                'ten_file' => 'BieuMauNopBai_101.zip',
                'ten_file_luu' => 'bieumaunopbai_648583.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_648583.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 4871.65,
                'nguoi_tao_id' => 88,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-05-27 05:29:00',
            ),
            101 => 
            array (
                'id' => 102,
                'ten_file' => 'BaoCaoDoAn_102.xlsx',
                'ten_file_luu' => 'baocaodoan_285488.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_285488.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 2786.13,
                'nguoi_tao_id' => 44,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-08-09 13:24:00',
            ),
            102 => 
            array (
                'id' => 103,
                'ten_file' => 'BieuMauNopBai_103.pptx',
                'ten_file_luu' => 'bieumaunopbai_764909.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_764909.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1452.08,
                'nguoi_tao_id' => 161,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-27 03:05:00',
            ),
            103 => 
            array (
                'id' => 104,
                'ten_file' => 'TaiLieuThamKhao_104.pdf',
                'ten_file_luu' => 'tailieuthamkhao_781180.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_781180.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 131.31,
                'nguoi_tao_id' => 241,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-03-28 03:31:00',
            ),
            104 => 
            array (
                'id' => 105,
                'ten_file' => 'KeHoachHoc_105.jpg',
                'ten_file_luu' => 'kehoachhoc_671194.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_671194.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 543.53,
                'nguoi_tao_id' => 116,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-06-30 18:51:00',
            ),
            105 => 
            array (
                'id' => 106,
                'ten_file' => 'HuongDanThucHanh_106.pdf',
                'ten_file_luu' => 'huongdanthuchanh_993077.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_993077.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 2132.17,
                'nguoi_tao_id' => 60,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-04-06 14:35:00',
            ),
            106 => 
            array (
                'id' => 107,
                'ten_file' => 'TaiLieuThamKhao_107.xlsx',
                'ten_file_luu' => 'tailieuthamkhao_305059.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_305059.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4288.9,
                'nguoi_tao_id' => 246,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-06-07 11:50:00',
            ),
            107 => 
            array (
                'id' => 108,
                'ten_file' => 'BieuMauNopBai_108.xlsx',
                'ten_file_luu' => 'bieumaunopbai_960270.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_960270.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 3242.05,
                'nguoi_tao_id' => 203,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-02-28 12:00:00',
            ),
            108 => 
            array (
                'id' => 109,
                'ten_file' => 'SlideBaiHoc_109.pptx',
                'ten_file_luu' => 'slidebaihoc_632216.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_632216.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 1453.84,
                'nguoi_tao_id' => 228,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-12-06 08:19:00',
            ),
            109 => 
            array (
                'id' => 110,
                'ten_file' => 'SlideBaiHoc_110.xlsx',
                'ten_file_luu' => 'slidebaihoc_104359.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_104359.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4505.93,
                'nguoi_tao_id' => 109,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-03-05 00:01:00',
            ),
            110 => 
            array (
                'id' => 111,
                'ten_file' => 'BaoCaoDoAn_111.docx',
                'ten_file_luu' => 'baocaodoan_981610.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_981610.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 4092.7,
                'nguoi_tao_id' => 212,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-01 19:20:00',
            ),
            111 => 
            array (
                'id' => 112,
                'ten_file' => 'DeCuongMonHoc_112.pptx',
                'ten_file_luu' => 'decuongmonhoc_699982.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_699982.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 4964.5,
                'nguoi_tao_id' => 64,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-08-23 12:12:00',
            ),
            112 => 
            array (
                'id' => 113,
                'ten_file' => 'BieuMauNopBai_113.zip',
                'ten_file_luu' => 'bieumaunopbai_968797.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_968797.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 305.33,
                'nguoi_tao_id' => 241,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-09-14 13:08:00',
            ),
            113 => 
            array (
                'id' => 114,
                'ten_file' => 'BieuMauNopBai_114.jpg',
                'ten_file_luu' => 'bieumaunopbai_863481.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_863481.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 909.9,
                'nguoi_tao_id' => 234,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-12-22 16:10:00',
            ),
            114 => 
            array (
                'id' => 115,
                'ten_file' => 'SlideBaiHoc_115.xlsx',
                'ten_file_luu' => 'slidebaihoc_204415.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_204415.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 3564.62,
                'nguoi_tao_id' => 35,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-07-01 03:40:00',
            ),
            115 => 
            array (
                'id' => 116,
                'ten_file' => 'BieuMauNopBai_116.zip',
                'ten_file_luu' => 'bieumaunopbai_983981.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_983981.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 3822.75,
                'nguoi_tao_id' => 237,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-24 17:10:00',
            ),
            116 => 
            array (
                'id' => 117,
                'ten_file' => 'SlideBaiHoc_117.pptx',
                'ten_file_luu' => 'slidebaihoc_197784.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_197784.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 511.66,
                'nguoi_tao_id' => 114,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-12 20:49:00',
            ),
            117 => 
            array (
                'id' => 118,
                'ten_file' => 'DeCuongMonHoc_118.zip',
                'ten_file_luu' => 'decuongmonhoc_129169.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_129169.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 3109.59,
                'nguoi_tao_id' => 142,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-04-21 18:24:00',
            ),
            118 => 
            array (
                'id' => 119,
                'ten_file' => 'DeCuongMonHoc_119.pdf',
                'ten_file_luu' => 'decuongmonhoc_575745.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_575745.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 3190.59,
                'nguoi_tao_id' => 202,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-02-01 05:15:00',
            ),
            119 => 
            array (
                'id' => 120,
                'ten_file' => 'SlideBaiHoc_120.jpg',
                'ten_file_luu' => 'slidebaihoc_411345.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_411345.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 1009.45,
                'nguoi_tao_id' => 218,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-10-09 23:49:00',
            ),
            120 => 
            array (
                'id' => 121,
                'ten_file' => 'HuongDanThucHanh_121.xlsx',
                'ten_file_luu' => 'huongdanthuchanh_791281.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_791281.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 306.16,
                'nguoi_tao_id' => 24,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-06-27 20:01:00',
            ),
            121 => 
            array (
                'id' => 122,
                'ten_file' => 'KeHoachHoc_122.jpg',
                'ten_file_luu' => 'kehoachhoc_208442.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_208442.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 599.11,
                'nguoi_tao_id' => 240,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-10-03 03:06:00',
            ),
            122 => 
            array (
                'id' => 123,
                'ten_file' => 'HuongDanThucHanh_123.docx',
                'ten_file_luu' => 'huongdanthuchanh_374721.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_374721.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 4478.29,
                'nguoi_tao_id' => 26,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-04-20 15:54:00',
            ),
            123 => 
            array (
                'id' => 124,
                'ten_file' => 'SlideBaiHoc_124.pptx',
                'ten_file_luu' => 'slidebaihoc_509783.pptx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_509783.pptx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
                'kich_thuoc' => 548.33,
                'nguoi_tao_id' => 206,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-02-23 13:04:00',
            ),
            124 => 
            array (
                'id' => 125,
                'ten_file' => 'TaiLieuThamKhao_125.xlsx',
                'ten_file_luu' => 'tailieuthamkhao_320511.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_320511.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 3452.32,
                'nguoi_tao_id' => 99,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-12-18 20:58:00',
            ),
            125 => 
            array (
                'id' => 126,
                'ten_file' => 'DeCuongMonHoc_126.xlsx',
                'ten_file_luu' => 'decuongmonhoc_288540.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/decuongmonhoc_288540.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 1528.84,
                'nguoi_tao_id' => 234,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-08-01 21:36:00',
            ),
            126 => 
            array (
                'id' => 127,
                'ten_file' => 'KeHoachHoc_127.jpg',
                'ten_file_luu' => 'kehoachhoc_996332.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_996332.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 205.68,
                'nguoi_tao_id' => 252,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-01-17 11:30:00',
            ),
            127 => 
            array (
                'id' => 128,
                'ten_file' => 'KeHoachHoc_128.zip',
                'ten_file_luu' => 'kehoachhoc_673028.zip',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_673028.zip',
                'loai_file' => 'application/zip',
                'kich_thuoc' => 74.82,
                'nguoi_tao_id' => 136,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-01 08:59:00',
            ),
            128 => 
            array (
                'id' => 129,
                'ten_file' => 'SlideBaiHoc_129.pdf',
                'ten_file_luu' => 'slidebaihoc_735553.pdf',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_735553.pdf',
                'loai_file' => 'application/pdf',
                'kich_thuoc' => 196.3,
                'nguoi_tao_id' => 8,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-07-15 16:48:00',
            ),
            129 => 
            array (
                'id' => 130,
                'ten_file' => 'SlideBaiHoc_130.docx',
                'ten_file_luu' => 'slidebaihoc_482615.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_482615.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 618.2,
                'nguoi_tao_id' => 58,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-03-02 10:08:00',
            ),
            130 => 
            array (
                'id' => 131,
                'ten_file' => 'TaiLieuThamKhao_131.docx',
                'ten_file_luu' => 'tailieuthamkhao_863094.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_863094.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 3473.43,
                'nguoi_tao_id' => 35,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-01 08:30:00',
            ),
            131 => 
            array (
                'id' => 132,
                'ten_file' => 'TaiLieuThamKhao_132.docx',
                'ten_file_luu' => 'tailieuthamkhao_465484.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/tailieuthamkhao_465484.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 3555.01,
                'nguoi_tao_id' => 169,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-28 14:47:00',
            ),
            132 => 
            array (
                'id' => 133,
                'ten_file' => 'BieuMauNopBai_133.xlsx',
                'ten_file_luu' => 'bieumaunopbai_637559.xlsx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/bieumaunopbai_637559.xlsx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                'kich_thuoc' => 4734.41,
                'nguoi_tao_id' => 239,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-08-16 08:11:00',
            ),
            133 => 
            array (
                'id' => 134,
                'ten_file' => 'HuongDanThucHanh_134.docx',
                'ten_file_luu' => 'huongdanthuchanh_511907.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_511907.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 559.33,
                'nguoi_tao_id' => 206,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-03-26 18:19:00',
            ),
            134 => 
            array (
                'id' => 135,
                'ten_file' => 'SlideBaiHoc_135.docx',
                'ten_file_luu' => 'slidebaihoc_857135.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/slidebaihoc_857135.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 2464.77,
                'nguoi_tao_id' => 229,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-05-02 13:38:00',
            ),
            135 => 
            array (
                'id' => 136,
                'ten_file' => 'HuongDanThucHanh_136.jpg',
                'ten_file_luu' => 'huongdanthuchanh_955524.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/huongdanthuchanh_955524.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 1627.81,
                'nguoi_tao_id' => 30,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-10-14 12:27:00',
            ),
            136 => 
            array (
                'id' => 137,
                'ten_file' => 'KeHoachHoc_137.docx',
                'ten_file_luu' => 'kehoachhoc_470058.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/kehoachhoc_470058.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1901.1,
                'nguoi_tao_id' => 164,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-05-20 02:28:00',
            ),
            137 => 
            array (
                'id' => 138,
                'ten_file' => 'BaiGiang_138.docx',
                'ten_file_luu' => 'baigiang_636196.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baigiang_636196.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 1302.67,
                'nguoi_tao_id' => 107,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-11-27 19:52:00',
            ),
            138 => 
            array (
                'id' => 139,
                'ten_file' => 'GiaoTrinh_139.jpg',
                'ten_file_luu' => 'giaotrinh_469364.jpg',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/giaotrinh_469364.jpg',
                'loai_file' => 'image/jpeg',
                'kich_thuoc' => 2021.62,
                'nguoi_tao_id' => 32,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2024-08-03 10:27:00',
            ),
            139 => 
            array (
                'id' => 140,
                'ten_file' => 'BaoCaoDoAn_140.docx',
                'ten_file_luu' => 'baocaodoan_357234.docx',
                'duong_dan' => 'https://res.cloudinary.com/ckc-classroom/files/baocaodoan_357234.docx',
                'loai_file' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                'kich_thuoc' => 409.57,
                'nguoi_tao_id' => 171,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2025-02-15 11:09:00',
            ),
            140 => 
            array (
                'id' => 141,
                'ten_file' => 'ckc_class_v4_seed_data.sql',
                'ten_file_luu' => 'gtzkjoyacrcfupraqaim.tmp',
                'duong_dan' => 'https://res.cloudinary.com/dnbmqrb2z/raw/upload/v1782847359/files/gtzkjoyacrcfupraqaim.tmp',
                'loai_file' => 'sql',
                'kich_thuoc' => 1391480.0,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-30 19:22:40',
            ),
            141 => 
            array (
                'id' => 142,
                'ten_file' => 'ckc_class_v4.sql',
                'ten_file_luu' => 't0fhifp8givfduz70lkk.tmp',
                'duong_dan' => 'https://res.cloudinary.com/dnbmqrb2z/raw/upload/v1782847362/files/t0fhifp8givfduz70lkk.tmp',
                'loai_file' => 'sql',
                'kich_thuoc' => 33080.0,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-30 19:22:42',
            ),
            142 => 
            array (
                'id' => 143,
                'ten_file' => 'ckc_class_v4_seed_data.sql',
                'ten_file_luu' => 'ocoerqq9c2uuslyss5u3.tmp',
                'duong_dan' => 'https://res.cloudinary.com/dnbmqrb2z/raw/upload/v1782847458/assignments/ocoerqq9c2uuslyss5u3.tmp',
                'loai_file' => 'sql',
                'kich_thuoc' => 1391480.0,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-30 19:24:19',
            ),
            143 => 
            array (
                'id' => 144,
                'ten_file' => 'ckc_class_v4_seed_data.sql',
                'ten_file_luu' => 'pbbktdkdduuscfghu0iq.tmp',
                'duong_dan' => 'https://res.cloudinary.com/dnbmqrb2z/raw/upload/v1782847723/assignments/pbbktdkdduuscfghu0iq.tmp',
                'loai_file' => 'sql',
                'kich_thuoc' => 1391480.0,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-30 19:28:43',
            ),
            144 => 
            array (
                'id' => 145,
                'ten_file' => 'ckc_class_v4.sql',
                'ten_file_luu' => 'eg5qahygzblshhp7puyn.tmp',
                'duong_dan' => 'https://res.cloudinary.com/dnbmqrb2z/raw/upload/v1782847725/assignments/eg5qahygzblshhp7puyn.tmp',
                'loai_file' => 'sql',
                'kich_thuoc' => 33080.0,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-30 19:28:45',
            ),
            145 => 
            array (
                'id' => 146,
                'ten_file' => '1778917666953_2819620676576697280_g7565388278367799324_2ea01ebe4410f169ef070191981fd56c.jpg',
                'ten_file_luu' => 'fw1hlwfsouiaokbbah3s.jpg',
                'duong_dan' => 'https://res.cloudinary.com/dnbmqrb2z/image/upload/v1782852640/assignments/fw1hlwfsouiaokbbah3s.jpg',
                'loai_file' => 'jpg',
                'kich_thuoc' => 298123.0,
                'nguoi_tao_id' => 22,
                'trang_thai' => 'dang_su_dung',
                'ngay_tao' => '2026-06-30 20:50:41',
            ),
        ));
        
        
    }
}