'use client';

import React, { useState } from 'react';
import styles from './AdminCreateStudents.module.css';

export default function CreateStudentForm() {
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitStatus, setSubmitStatus] = useState<'idle' | 'success'>('idle');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    // Simulate API call
    setTimeout(() => {
      setSubmitStatus('success');
      setTimeout(() => {
        setSubmitStatus('idle');
        setIsSubmitting(false);
        // In real app, redirect here
      }, 2000);
    }, 1500);
  };

  return (
    <div className={styles.layoutGrid}>
      {/* Left Column: Profile Picture & Core Info */}
      <div className={styles.leftColumn}>
        <section className={`${styles.card} ${styles.cardCenter}`}>
          <div className={styles.avatarUploadWrapper}>
            <div className={styles.avatarBox}>
              <span className={`material-symbols-outlined ${styles.avatarIcon}`}>add_a_photo</span>
            </div>
            <div className={styles.avatarOverlay}>
              {/* Hidden Input Trigger */}
            </div>
          </div>
          <h3 className={styles.cardTitle}>Profile Picture</h3>
          <p className={styles.avatarHelpText}>
            Upload a high-resolution portrait. Max size 10MB. JPG or PNG.
          </p>
          <button className={styles.btnUpload} type="button">Upload Image</button>
        </section>

        <section className={styles.card}>
          <h3 className={styles.cardTitle}>
            <span className={`material-symbols-outlined ${styles.cardTitleIcon}`}>assignment_ind</span>
            Identity Details
          </h3>
          <div className={styles.formGroup}>
            <label className={styles.formLabel}>Student ID</label>
            <input
              className={`${styles.formInput} ${styles.formInputDisabled}`}
              type="text"
              value="STU-2024-0892"
              disabled
            />
            <span className={styles.helpText}>*Auto-generated by system</span>
          </div>
          <div className={styles.formGroup}>
            <label className={styles.formLabel}>Study Status</label>
            <select className={`${styles.formInput} ${styles.formSelect}`}>
              <option>Active / Full-time</option>
              <option>On-Leave</option>
              <option>Internship</option>
              <option>Graduated</option>
            </select>
          </div>
        </section>
      </div>

      {/* Right Column: Personal & Academic Info */}
      <div className={styles.rightColumn}>
        <form onSubmit={handleSubmit} className={styles.leftColumn}>
          {/* Personal Info Card */}
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={`material-symbols-outlined ${styles.cardTitleIcon}`}>person</span>
              Personal Information
            </h3>
            <div className={styles.grid2Col}>
              <div className={styles.colSpan2}>
                <label className={styles.formLabel}>Full Name</label>
                <input
                  className={styles.formInput}
                  type="text"
                  placeholder="Enter student's full name"
                  required
                />
              </div>
              <div>
                <label className={styles.formLabel}>Date of Birth</label>
                <input
                  className={styles.formInput}
                  type="date"
                  required
                />
              </div>
              <div>
                <label className={styles.formLabel}>Gender</label>
                <div className={styles.radioGroup}>
                  <label className={styles.radioLabel}>
                    <input type="radio" name="gender" className={styles.radioInput} defaultChecked />
                    <span className={styles.radioText}>Male</span>
                  </label>
                  <label className={styles.radioLabel}>
                    <input type="radio" name="gender" className={styles.radioInput} />
                    <span className={styles.radioText}>Female</span>
                  </label>
                </div>
              </div>
            </div>
          </div>

          {/* Contact Info Card */}
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={`material-symbols-outlined ${styles.cardTitleIcon}`}>contact_mail</span>
              Contact Information
            </h3>
            <div className={styles.grid2Col}>
              <div>
                <label className={styles.formLabel}>Email Address</label>
                <input
                  className={styles.formInput}
                  type="email"
                  placeholder="student@university.edu"
                  required
                />
              </div>
              <div>
                <label className={styles.formLabel}>Phone Number</label>
                <input
                  className={styles.formInput}
                  type="tel"
                  placeholder="+84 000 000 000"
                />
              </div>
              <div className={styles.colSpan2}>
                <label className={styles.formLabel}>Current Address</label>
                <textarea
                  className={`${styles.formInput} ${styles.formTextarea}`}
                  rows={3}
                  placeholder="Street name, District, City..."
                ></textarea>
              </div>
            </div>
          </div>

          {/* Academic Placement Card */}
          <div className={styles.card}>
            <h3 className={styles.cardTitle}>
              <span className={`material-symbols-outlined ${styles.cardTitleIcon}`}>school</span>
              Academic Placement
            </h3>
            <div className={styles.grid2Col}>
              <div>
                <label className={styles.formLabel}>Department</label>
                <select className={`${styles.formInput} ${styles.formSelect}`}>
                  <option>Computer Science</option>
                  <option>Business Administration</option>
                  <option>Information Technology</option>
                  <option>Electrical Engineering</option>
                  <option>Digital Marketing</option>
                </select>
              </div>
              <div>
                <label className={styles.formLabel}>Class Code</label>
                <select className={`${styles.formInput} ${styles.formSelect}`}>
                  <option>CS-2024-A</option>
                  <option>CS-2024-B</option>
                  <option>BA-2024-K12</option>
                  <option>IT-PRO-24</option>
                </select>
              </div>
            </div>
          </div>

          {/* Form Actions */}
          <div className={styles.formActions}>
            <button type="button" className={styles.btnDiscard}>Discard Draft</button>
            <button
              type="submit"
              className={styles.btnSubmit}
              disabled={isSubmitting}
              style={{ backgroundColor: submitStatus === 'success' ? '#059669' : '' }}
            >
              {isSubmitting && submitStatus === 'idle' ? (
                <>
                  <span className="material-symbols-outlined" style={{ animation: 'spin 1s linear infinite' }}>sync</span>
                  Processing...
                </>
              ) : submitStatus === 'success' ? (
                <>
                  <span className="material-symbols-outlined">check_circle</span>
                  Added Successfully
                </>
              ) : (
                <>
                  <span className="material-symbols-outlined">person_add</span>
                  Thêm Sinh Viên
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}
